### ISSUE TITLE
Instabilities in RMSD of equal conformations?

### ISSUE THREAD

**Issue by ag1989** [mdtraj/mdtraj#1006]
When calculating a distance matrix for a trajectory I observed some small difference in computing RMSD between the exactly same conformations/frames. Commonly I would expect that all diag elements of my matrix should be 0. But for a not so small portion of this entries I get differing values. I made a short check with the following code. Atom indices are just a few Ca-atoms (23 in total). 
```python
print(md.rmsd(traj[32], traj[32], atom_indices=cluster_ident))
```
As output I got the following
```python
[ 0.00089148]
```
I know it is just a very minor difference but I was wondering if this is still in the numerical variance of the fitting procedure in the QCP method?

**Comment by rmcgibbo** [comment]
Yes, this is about the accuracy of the algorithm.

**Comment by ag1989** [comment]
Okay, good to know and thank you. You can close this issue.

**Comment by rmcgibbo** [comment]
I don't recall the exact code, but I believe that in one part of the rmsd implementation, it has the potential to just short circuit and return `0` if it can prove that the two frames being compared are just pointers to the same chunk of memory, but I don't know why that doesn't apply here (it could be because of `atom_indices`).
