### ISSUE TITLE
atom-names in MET residue

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1016]
Hi, perhaps this is a no-brainer (it's late...), but why are the hydrogens HB1 and HB2 being renamed to HB2 and HB3, respectively? 

Compare lines/atoms 10 & 11 between the mdtraj's output and a the command line interface ("head"). Lines 13 & 14 work as well
![snap](https://cloud.githubusercontent.com/assets/7518004/12123645/6a47a62a-b3e2-11e5-9061-f9c49cee9b44.png)

**Comment by swails** [comment]
[Because that's how the PDB names them](http://www.rcsb.org/pdb/files/ligand/MET.cif) and OpenMM adheres to that standard as much as possible. And MDTraj uses (a modified copy of) OpenMM's PDB parser/structure.

**Comment by gph82** [comment]
Hi, thanks very much, was not aware that that was the PDB standard. I familiarized with gromacs' topology files, e.g. amber99sb-ildn.ff/aminoacids.rtp:
```
[ MET ]
 [ atoms ]
     N    N           -0.41570     1
     H    H            0.27190     2
    CA    CT          -0.02370     3
    HA    H1           0.08800     4
    CB    CT           0.03420     5
   HB1    HC           0.02410     6
   HB2    HC           0.02410     7
    CG    CT           0.00180     8
   HG1    H1           0.04400     9
   HG2    H1           0.04400    10
    SD    S           -0.27370    11
    CE    CT          -0.05360    12
   HE1    H1           0.06840    13
   HE2    H1           0.06840    14
   HE3    H1           0.06840    15
     C    C            0.59730    16
     O    O           -0.56790    17
```

Been using mdtraj to work with gromacs for over 2y and only now I noticed this.

Good to know!

**Comment by swails** [comment]
It seems that GROMACS is using some weird PDB v.2/PDB v.3 hybrid.  For instance, PDB v.2 used names `1HB` and `2HB`, whereas PDB v.3 uses `HB2` and `HB3`.

**Comment by gph82** [comment]
I see. Well now that you mention, this has popped on the newer 5.xx (>4.6) versions of gromacs. I'll look more into it tomorrow. I'm hopping it's just a naming convention, which grompp can safely ignore the mismatched-naming warnings. Thanks

**Comment by gph82** [comment]
nope, nothing to do with gromacs version change...so I guess this has always been there and only now I notice... I is it worth offering a PDB_ver kwarg when loading the geometry, as long as this is not changed in gromacs?

**Comment by swails** [comment]
> is it worth offering a PDB_ver kwarg when loading the geometry, as long as this is not changed in gromacs?

Can you be more precise about this proposal and exactly what it is supposed to be doing?

**Comment by gph82** [comment]
Sure! 

My scenario is using mdtraj to modify a geometry that i'll later feed to gromacs' grompp (the parser before the actual run). Even tough I loaded what I assume is PDB v.2 (or a hybrid with PDB v.3, as you mention), once I use geom.save('out.pdb'), it's been written with PDB v.3, and grompp will complain about the naming convention. I can skip with allowing for a number warnings (-maxwarn 1), so for now I can move on (and thanks for the interest and answers, BTW).

What I mean with PDB kwarg could be something along the lines of
```
geom = md.load('file_with_pdbv2hybridv3_that_comes_from_gromacs.pdb', PDB_ver3=False)

md.load?
""""
PDB_ver3: boolean, default True
                  If set to false, mdtraj will not update the atom-naming convention of the input to the PDB v.3 convention, but leave it as is. PDB_ver=False is typically used for legacy topologies that work still with PDB v.2 (or hybrids thereof) and is not recommended. 
""""
```

Too bad a design idea? md.load is the point of entry to mdtraj and I don't want the input cluttered either, hence the kwarg at the highest level.

**Comment by swails** [comment]
Let's keep this open, since it's an active discussion.  I would actually vote more along the lines of a kwarg `standardize_names` that defaults to `True` and can be explicitly turned off.  I think MDTraj should try to write an RCSB-valid PDB file first, and have some options to make small violations if there is a real use-case to justify.

I'll let others weigh in here as well.

**Comment by gph82** [comment]
I like that more, thanks very much! Perhaps there's no need, since the maxwarn 1 option works fine.

**Comment by swails** [comment]
I think there are instances where *not* changing the atom (and/or residue) names is desirable (and, of course, instances where adhering to PDB standards *is*).  At the very least, this can lead to a scenario where reading a PSF or prmtop and an equivalent PDB file has name mismatches, since PDB atom names are standardized whereas that's not the case for other file formats.

**Comment by gph82** [comment]
yeah I was also thinking that, but i know you guys have been having a similar issue here https://github.com/mdtraj/mdtraj/issues/996 so I guess there's already some thought going on.

**Comment by swails** [comment]
> yeah I was also thinking that, but i know you guys have been having a similar issue here #996 so I guess there's already some thought going on.

That's related, but a different discussion, really.

**Comment by rmcgibbo** [comment]
This request (adding the option to skip atom / residue name replacements) has come up before. I think it would be a good improvement to make, even though it could create some other bugs.
- Some other code-paths inside MDTraj or in other tools might expect that PDB names are followed and not handle the deviation properly. For example, for writing the CONNECT records to PDB files, MDTraj checks the residue name, since you're not supposed to write connect records for bonds within standard residues. But if you don't apply the renaming rules to residue names, something like
```
>>> md.load('model.pdb'), standardize_names=False).save('new.pdb')
```
might not get the proper connect records. This isn't too serious, but there could be other things.

----------------------


If anyone would like to implement and contribute this feature, I suspect the way to go about it is to:
- add `standard_names=True` to the signatures here: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L96-L97 and https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L238
- use that option to toggle the code here: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L512-L513
- The prmtop and psf loaders likely would also need to acquire this toggle switch as well, since iirc they apply the same replacement rules when loading data.

**Comment by gph82** [comment]
Hi @rmcgibbo , this seems to be doing the trick for me, following your instructions https://github.com/gph82/mdtraj/commit/7a3f4a62f233fc973be87513b8c24cdcd4f31a0b

**Comment by rmcgibbo** [comment]
Cool, want to file a PR for that?

**Comment by gph82** [comment]
wait, I just noticed the last commit was missing, can you take a look now?

On 02/29/2016 07:26 PM, Robert T. McGibbon wrote:
> Cool, want to file a PR for that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1016#issuecomment-190321676>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by rmcgibbo** [comment]
can you make a pull request with those commits?

**Comment by gph82** [comment]
here 095d235da6c2e2d24452f02e6818a7fd1a70ec39, In particular here: https://github.com/mdtraj/mdtraj/blob/095d235da6c2e2d24452f02e6818a7fd1a70ec39/mdtraj/formats/pdb/pdbfile.py#L154

**Comment by gph82** [comment]
against master or 1.6 branch?

**Comment by gph82** [comment]
sorry, I'm a bit confused, against what branch?

**Comment by rmcgibbo** [comment]
Against master.

**Comment by rmcgibbo** [comment]
(General pattern is that all PRs should go to master, and then some bugfixes may or may not be backported to previous feature branches for bugfix releases.)

**Comment by gph82** [comment]
Thanks, I now noticed I've got as origin
origin  https://github.com/rmcgibbo/mdtraj.git (fetch)
origin  https://github.com/rmcgibbo/mdtraj.git (push)

and have to rebase to the mdtraj/mdtraj master branch before PRing, right?

On 02/29/2016 07:42 PM, Robert T. McGibbon wrote:
> (General pattern is that all PRs should go to master, and then some bugfixes may
> or may not be backported to previous feature branches for bugfix releases.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1016#issuecomment-190326158>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by rmcgibbo** [comment]
You could change it (just edit .git/config with your text editor), but I think it'll work either way. But yeah, you either want to merge or rebase on mdtraj/mdtraj@master to have a clean PR.

**Comment by gph82** [comment]
just did the rebase and PR. Tests are minimal (nothing breaks). I don't know your policy for adding new .pdb files for the sake of actual testing. I could provide a non standard pdb.gz if needed

**Comment by BJWiley233** [comment]
FYI updated link format for residue CIF files is https://files.rcsb.org/ligands/view/<residue>.cif as in https://files.rcsb.org/ligands/view/MET.cif
