### ISSUE TITLE
Several example notebooks broken 

### ISSUE THREAD

**Issue by ctk3b** [mdtraj/mdtraj#1049]
The following notebooks display various errors on the website:
http://mdtraj.org/latest/examples/clustering.html
http://mdtraj.org/latest/examples/hbonds.html
http://mdtraj.org/latest/examples/iterload.html
http://mdtraj.org/latest/examples/nmr.html
http://mdtraj.org/latest/examples/openmm.html
http://mdtraj.org/latest/examples/ramachandran-plot.html
http://mdtraj.org/latest/examples/two-pass-clustering.html

Has anyone automated rebuilding all of these?

**Comment by mpharrigan** [comment]
Good spot. I'll work on fixing this

**Comment by ctk3b** [comment]
I haven't tried this out but looks promising: https://github.com/paulgb/runipy

**Comment by mpharrigan** [comment]
We actually use that integrated with sphinx to automatically run the notebooks on each pull request merge. The problem is the notebooks are actually broken!

I'm going to fix the notebooks and also downgrade the "kernel" to python2 since we switched back to that for #1042 

I'd like to port the work I did on modernizing this whole schtick in msmbuilder to this repository but that's for another day

**Comment by mpharrigan** [comment]
Can you take a look? (make sure you refresh)

the clustering one is still broken

**Comment by mpharrigan** [comment]
Ok, I think they're all fixed. Can you take a second look

**Comment by ctk3b** [comment]
Looks good, no errors!

**Comment by mpharrigan** [comment]
The released versions are fixed as well http://mdtraj.org/1.6.2/examples/clustering.html
