### ISSUE TITLE
image_molecules IndexError

### ISSUE THREAD

**Issue by jadeshi** [mdtraj/mdtraj#1084]
Wondering if anyone else has come across this error when trying to use image_molecules. The trajectory is an xtc for which I supplied a pdb topology with PBC's, and loads into mdtraj fine.

```
IndexError                                Traceback (most recent call last)
<ipython-input-46-7ee548d6ab04> in <module>()
----> 1 traj.image_molecules()

/home/jadeshi/miniconda/lib/python2.7/site-packages/mdtraj-1.7.0.dev0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.pyc in image_molecules(self, inplace)
   1901             used_anchors = [0]
   1902             available_anchors = list(range(1, num_anchors))
-> 1903             min_anchor_dist = anchor_dist[0, :]
   1904 
   1905             # Add in anchors one at a time, always taking the one that is nearest an existing anchor.

IndexError: index 0 is out of bounds for axis 0 with size 0
```

Thanks!

**Comment by mpharrigan** [comment]
I'm seeing this as well, incidentally on the system I used to originally test the code. @peastman do you have any ideas?

**Comment by peastman** [comment]
Does that mean this used to work, and then recently stopped working?  If someone can provide me with a file that shows the problem, I'll look into it.

**Comment by mpharrigan** [comment]
@jadeshi I could reproduce this when using a gro topology file, but not with pdb. From ipython, can you enter into pdb (python debugging) by entering `%pdb on` (so it will enter the debugger when an exception happens) and at the pdb prompt, type and report the values of

`atoms_cutoff`
`num_anchors`

**Comment by peastman** [comment]
Can you send me the files to reproduce this?

**Comment by mpharrigan** [comment]
I sent you mine, but I suspect @jadeshi 's issue might be different if he is using a pdb as he said

**Comment by peastman** [comment]
It looks like there are actually two problems.  One is clearly a bug.  The other isn't exactly a bug, but it could still possibly be handled better.

The first problem is that if it doesn't identify any anchor molecules, it throws this exception.  That will happen, for example, if every molecule in the topology is exactly the same size.  So if you called this function for a box of water, it would fail.  I can fix that.

The other problem is that your Topology doesn't include any bonds.  And bonds are how it identifies molecules.  Hence, it thinks that every atom is a separate molecule.  GRO files look a lot like PDB files, but they don't have as much information, and they may not follow any standard naming convention.  So it's really hard to create a proper Topology from one.  (OpenMM won't even try.  The only thing it will load from a GRO file is coordinates.  It expects you to also have a TOP file from which it can create the Topology).

So what should it do in this case?  It should probably just refuse to try to image the molecules, since it doesn't have enough information to do that.  On the other hand, there are cases where you might legitimately have no bonds, and every atom really is a separate molecule.  A box of argon gas, for example.  Perhaps we could check that there are no bonds, *and* there is at least one residue with multiple atoms?

**Comment by mpharrigan** [comment]
> The first problem is that if it doesn't identify any anchor molecules, it throws this exception. That will happen, for example, if every molecule in the topology is exactly the same size. So if you called this function for a box of water, it would fail. I can fix that.

I submitted a pr #1102 that at least gives a helpful error message

I'm fine with refusing gro topologies
