### ISSUE TITLE
PDB parsing issues

### ISSUE THREAD

**Issue by psolsson** [mdtraj/mdtraj#1129]
Parsing PDB-files where residues have atoms in a not strictly contiguous stretch gives rise to multiple residues. examples:
loading this one in mdtraj 1.7.2
[system-protein.pdb.zip](https://github.com/mdtraj/mdtraj/files/310935/system-protein.pdb.zip)
is understood as a topology with 78 residues; whereas it has only 39. 

Changing the atom ordering fixes the problem. As far as i can see there is no strict rules about the ordering of atoms according to the PDB format specification - the pdb parses well in other programs, vmd, pymol etc.

**Comment by rmcgibbo** [comment]
Thanks for the bug report and the example file.

**Comment by cclementi** [comment]
Hi, I would like to add to this issue, as I am having the same problem with the same file. 
This pdb file is created by vmd from a .mae file that is provided with the D.E. Shaw trajectories of the proteins simulated in their paper: Kresten Lindorff-Larsen, Stefano Piana, Ron O. Dror, and David E. Shaw, "How Fast-Folding Proteins Fold," Science, 334, 2011, 517-520.  All proteins from this set seem to have this issue. If the pdb file straight out of vmd is used as topology file in mdtraj to load the *.dcd files, it is understood as a longer protein because the atoms are not listed in the correct residue-after-residue order (all the H atoms are at the end). As Simon pointed out, other programs (like pymol) are able to interpret this pdb correctly. If the pdb is loaded and saved by pymol in a format that is mdtraj-friendly (with the atoms in the correct order), then it's not consistent with the corresponding *.dcd files anymore and if the *.dcd files are loaded in mdtraj the molecule appears all "scrambled".  
I hope I haven't confused things more. I can provide the files if needed.
Thanks!

**Comment by rmcgibbo** [comment]
Yes, this sounds like a problem. I think other users like @evanfeinberg may have come up with solutions. Unfortunately I don't really have time to fix this, but maybe other developers do. If either of you want to take a stab at fixing it in a pull request, that would be great too.

**Comment by rmcgibbo** [comment]
One thing which may be worth checking: the PDB-parsing code in mdtraj mostly originates from OpenMM, but it might be slightly outdated with respect to any bugfixes that have been recently added to OpenMM. So it may be worth checking if this issue exists in OpenMM, and it doesn't, there maybe be a very simple patch that could be applied.

**Comment by evanfeinberg** [comment]
Hi @cclementi and @rmcgibbo , thanks for reaching out. I too indeed have found this issue interoperating between Anton trajectories and mdtraj challenging. Honestly, I can't remember how I addressed it, but I wrote this code a long time ago for "fixing" Anton trajectories that have this fragmented residue problem. Maybe this will work for you? 

https://gist.github.com/evanfeinberg/608d13d2bcbdbe65dd4859bb3482027e

**Comment by bonimba87** [comment]
Hello @evanfeinberg, 
I have used the script you recommended and the issues mentioned above seem to be taken care of. Specifically, the true number of residues is retained, and no spurious additional residues (due to lack of atomic contiguity in the topology file) are observed. Thank you very much for your contribution!

**Comment by evanfeinberg** [comment]
Woot, thanks @bonimba87 , that makes my day! Glad to hear it helped. I highly recommend saving a frame of the "fixed" trajectory as a PDB and loading it up in PyMol/VMD/your-favorite-visualization-program to make sure everything looks OK.
