### ISSUE TITLE
Reintroduce faster SSE load4s where safe in geometry core

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1195]
cc: https://github.com/mdtraj/mdtraj/pull/1167

**Comment by tovrstra** [comment]
I'm happy to take a look at it but some guidance on how to solve this would be helpful. Ideas mentioned in #1167 were apparently not so good. 

The following may be better, but I'm not sure. For performance critical parts, we should use the fvec4 pointer constructor (`_mm_loadu_ps`) but not when the pointer is too close to the end of an array. We can use a simple `if` statement to avoid unsafe situations, e.g.

    if (offset <= size-4) {
        // happens nearly always
        pos = fvec4(xyz + offset);
    } else {
        // happens only very rarely
        pos = fvec4(xyz[offset], xyz[offset+1], xyz[offset+2], 0);
    }

I'm concerned that branching like this may kill performance as well. If the CPU could somehow figure out that the first branch is the most likely, it would nearly always fill the instruction pipeline with the correct code. That would be ideal. I'm not sure how that can be achieved. Maybe the standard branch prediction algorithms of common CPUs already deal with such cases efficiently?

**Comment by rmcgibbo** [comment]
Yes, I think that's the right way to do it. It's not worth stressing about branch prediction without profiling first.

**Comment by tovrstra** [comment]
OK. Thanks for the advice.

**Comment by peastman** [comment]
It's even better though if you can arrange that the array will be sufficiently padded so you don't need that check.  Wherever possible, that's the way to do it.

**Comment by tovrstra** [comment]
I understand the concept of padding (and I know how to do it in Python) but what is a good strategy adding the extra float(s)? I guess it is not so desirable to make a copy of xyz into an array with padding right before a low-level call because of the memory and CPU overhead? If padding is implemented in the trajectory class itself, it becomes ugly and it puts a lot of constraints on the rest of the code, which is not nice either.

**Comment by marscher** [comment]
I don't see why having this in the Trajectory class imposes constraints on the rest of the code. You create an array where the size is dividable by four, so n_atoms fit into it and create a view, which restricts it to the proper size. Since the native code always gets pointers with a size information (which is n_frames, n_atoms) we should be fine. The Python code just uses the size information from the ndarray view, which is also correct.

**Comment by tovrstra** [comment]
The following code would assure that the `_xyz` attribute always has an extra float, making it safe to use SSE instructions on the last atom in the last frame. I don't like it because it makes an extra copy, even if `value` already has an extra float allocated. (I don't think there is a way to check that?)

    @xyz.setter
    def xyz(self, value):
        "Set the cartesian coordinates of each atom in each simulation frame"
        if self.top is not None:
            # if we have a topology and its not None
            shape = (None, self.topology._numAtoms, 3)
        else:
            shape = (None, None, 3)

        value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
                            warn_on_cast=False, add_newaxis_on_deficient_ndim=True)

        if not hasattr(self, '_xyz') or self._xyz.shape != value.shape:
            self._xyz = np.zeros(value.size+1, np.float32)[:value.size].reshape(value.shape)
        else:
            self._xyz[:] = value
        self._rmsd_traces = None

**Comment by mpharrigan** [comment]
@peastman do you have any ideas for how to get this working

**Comment by peastman** [comment]
Is there a way we can check whether it already has the extra padding?  That way we only need to make a copy if it doesn't.  Then we can have all the file loaders create padded arrays right from the beginning, so usually the copy won't be necessary.

We also could make the padding be an option to `ensure_type()`, since that will often have to create a copy anyway.

**Comment by tovrstra** [comment]
I agree. There should be a way to test if some padding is already present. Keep in mind that in NumPy, the term padding is (also?) used for something else:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

**Comment by tovrstra** [comment]
The `base` attribute seems to be the way to do it:

	import numpy as np
	a = np.array([1, 2, 3])
	print a.base
	b = a[:2]
	print b.base.size - b.size
	c = b[:1]
	print c.base.size - c.size

In the last two print lines, the `base` attribute refers to `a`, so this way you can get the owner of the memory and the number of elements "after the array". It would indeed be ideal to add an option to `ensure_type` to deal with this. The io functions can be easily designed to create proper arrays when reading trajectories.
