### ISSUE TITLE
Atom selection 'not resid > x' etc. weird behavior

### ISSUE THREAD

**Issue by rafwiewiora** [mdtraj/mdtraj#1209]
I was using atom selection expressions such as:
``` python
top.select('not resid < x')
top.select('not resid <= x')
top.select('not resid > x')
top.select('not resid >= x')
```

these behave weirdly - the first two actually return the same as `top.select('all')`, the last two return empty arrays. Parentheses (e.g. `top.select('not (resid < x)')`) make them work as expected, but: a) it's not clear to me why you need the parentheses, b) the non-parentheses versions give no warning or exception that the returned array is not what you wanted.

**Comment by rmcgibbo** [comment]
I assume the reason is that the precedence of 'not' is too low. That's probably a bug. I wouldn't expect it to give an warning or exception though.

**Comment by mpharrigan** [comment]
I think the precedence of `not` may be too high. `(not resid) < x`

**Comment by dwhswenson** [comment]
Bumping this issue. I came across it in the following context:

```
REMARK   1 fake_traj.pdb (part of a test)
CRYST1   25.000   25.000   25.000  90.00  90.00  90.00 P 1          1
HETATM    1  C1  XXX A   1       0.250   0.750   0.000  1.00  0.00           C
HETATM    2  C2  XXX A   1       0.250   1.250   0.000  1.00  0.00           C
```

```python
import mdtraj as md
top = md.load("./fake_traj.pdb").topology
top.select("symbol != 'H'")
# array([0, 1])
top.select("not symbol == 'H'")
# array([], dtype=float64)
```

Obviously, I would expect those two to be the same. And yes, using `"not (symbol == 'H')"` gives the correct result.

By the way, I think this worked correctly in an earlier version of MDTraj. At least, I found this when I came back to some code that I'm pretty sure used to work (around spring of 2016) where I had used `"not water and not symbol == 'H'"` as a default selection to select heavy atoms.

Workarounds are easy and obvious, so that what I'll do for now.
