### ISSUE TITLE
Sodium atom recognized as Nitrogen

### ISSUE THREAD

**Issue by bencoscia** [mdtraj/mdtraj#1278]
I need a list of element names for all atoms in my system. I used the syntax [a.element.symbol for a in t.topology.atoms] to generate the list. Unfortunately all of the NA 's are being interpreted as N 's. 
Is this a bug or is there any workaround for this?

I put the files necessary to reproduce this here: https://drive.google.com/drive/folders/0B2Rn9uPRgObMX2k0aTVJLWZNLUk?usp=sharing

**Comment by cing** [comment]
This is a bug, but there are also workarounds. 

There's no problem with element detection code:
```
>>> from mdtraj.core import element as elem
>>> elem.get_by_symbol("NA")
(11, 'sodium', 'Na', 22.989769282, 0.136)
```
The problem is the heuristic used for converting atom names to elements uses the first character of the atom [here from GRO](https://github.com/mdtraj/mdtraj/blob/c22c829baf7e0b0956fd29fc9b5d524d183679a5/mdtraj/formats/gro.py#L315) and [here for PDB](https://github.com/mdtraj/mdtraj/blob/c22c829baf7e0b0956fd29fc9b5d524d183679a5/mdtraj/formats/pdb/pdbstructure.py#L760). The idea with that code would be to take an atom name like "C18" and only use the first character "C" to deduce the element, which works for all protein atoms. This is what happens for "NA" being converted to "N", certainly in the case of the GRO parser. The PDB parser uses the first two characters, but if your atom name is " NA" instead of "NA ", notice the position of the space, then it'll be nitrogen again. That's an easy fix for PDB, `self.name_with_spaces.strip()[0:2].lstrip("0123456789")` instead of `self.name_with_spaces[0:2].strip().lstrip("0123456789")`

That being said, but it's probably easiest for you to just use a PDB file instead of a GRO for your topology and ensure that you either have NA left justified in the atom name columns, or use recommended columns 77-78 to indicate the element. For an example of a PDB file with an Na+ that has proper element detection, see [5BZB](http://www.rcsb.org/pdb/explore.do?structureId=5bzb)

**Comment by peastman** [comment]
The problem is more fundamental than that: GRO files don't record the elements of atoms.  That means the best it can do is try to guess the element based on the atom name, but it's only a guess.  That information simply isn't present in the input file.  That's why it's better to load the topology from a format like PDB does that record elements.

**Comment by bencoscia** [comment]
That makes sense. Using a .pdb as the topology with the elements defined works well. Since I only have a .gro to work with, I used gromacs (gmx editconf) to convert to .pdb format and then added the element names in the appropriate column using python.
