### ISSUE TITLE
traj.save() converts HETATM entries to ATOM

### ISSUE THREAD

**Issue by hectormartinezdev** [mdtraj/mdtraj#1327]
Hi!

I think that this is a **bug** regarding the use of MDTraj.

Versions:
```
python -V
Python 2.7.12

python -c "import mdtraj; print mdtraj.version.full_version"
2.0.0.dev0+44df6838e4eb8f3856c1022c20c8186722751ed2
```

I have my PDB with HETATMs. When I open it and save it, mdtraj rename the HETATM entries as ATOM. But if I select only the protein with `topology.select("protein")`, slice the trajectory and save it, it doesn't save the HETATM.

Steps to reproduce:
```
import mdtraj as md
md.load("2m9r.pdb").save("renamed_as_atoms.pdb")
md.load("2m9r.pdb").atom_slice(md.load("2m9r.pdb").topology.select("protein")).save("removed_hetatms.pdb")
```

The PDB file: [2m9r.txt](https://github.com/mdtraj/mdtraj/files/1680855/2m9r.txt)

Is this an expected behaviour? If it's expected, sorry for bothering. If not, we spotted a bug?

Thank you!

**Comment by rmcgibbo** [comment]
You can see [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L347) that when writing out a PDB file it always uses ATOM.

**Comment by rmcgibbo** [comment]
There's nothing unexpected about this behavior, but I agree it would probably be better to properly write HETATM when appropriate.

**Comment by hmarlo** [comment]
Yeah, probably I'm getting unexpected results due to this behaviour, since the software in which I pipe the saved trajectory, read the type of record of each atom.

Looking at the [Atom](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L1431) code on `topology.py`, there is no attribute to keep track of the record name (specification [here](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM)).

I digged in the PDB format and in the Atom class in `pdbstructure.py` ([here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbstructure.py#L637)) there is a `self._record_name`, but it seems that doesn't get that far. In this class, the method `_pdbstring` ([here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbstructure.py#L843)) is called on the method `write`, and it writes the `self._record_name`. 

So it seems that is kind of implemented, but the `pdbfile.py` that you linked, the attribute is not used. Maybe changing the "ATOM" for a `%s` and complete it with self._record_name will suffice.

I will do a few tests and open a merge request. Is that OK?

**Comment by rmcgibbo** [comment]
1. I'm pretty sure that all of the writing functionality goes through pdbfile.py, and skipps pdbstructure.py.
2. If the goal is to write ATOM/HETATM records correctly, we should be able to do that regardless of whether or not the topology being written was loaded from a PDB, loaded from another supported format, or constructed in memory. That means figuring out what the record name is supposed to be, I think, not just round-tripping between the reader and writer.
3. Yeah, pull requests with tests are the way to go. Thanks for looking into this.

**Comment by peastman** [comment]
The decision of whether to write ATOM or HETATM can be based solely on the residue name.  See the definition of heterogens at http://www.wwpdb.org/documentation/file-format-content/format33/sect4.html#HET.

**Comment by hmarlo** [comment]
Better than guessing which will be the record name of the entry (HETATM or ATOM), we can use the record name from the original PDB? Or we should try to correct those record names?

With `dir(atom)` printed [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L347), `_record_name` is not among the options printed, so it's not using the `Atom` class defined in pdbstructre, or it is changed during the processing.

**Comment by peastman** [comment]
I would never assume the record names in the input file were correct. :)

**Comment by hmarlo** [comment]
OK! So we have our list:

- Standard aminoacids: ALA, ARG, ASN, ASP, CYS, GLN, GLU, HIS, ILE, LEU, LYS, MET, PHE, PRO, SER, THR, TRP, TYR and VAL
- Nucleic acids: C, G, A, U, I, DC, DG, DA, DU, DT and DI
- Unknown: UNK and N

Is this right?

**Comment by hmarlo** [comment]
I've made a first approach, should I make a branch from master or other branch  @rmcgibbo ? Then I will make a pull request referencing this issue and we can polish the modifications there.
