### ISSUE TITLE
Null atom selection when residue name include digits

### ISSUE THREAD

**Issue by andrrizzi** [mdtraj/mdtraj#1336]
It seems that something goes wrong with the atom selection when the residue name contains a number. With:
```python
import mdtraj

topology = mdtraj.load_topology('SYSTEM.prmtop')
print('N atoms: ', topology.n_atoms)
print('N residues', topology.n_residues)
print('Residue names: ', {residue.name for residue in topology.residues})
print('N LIG atoms: ', len(topology.select('resname LIG')))
print('N 0C9 atoms: ', len(topology.select('resname 0C9')))
```
I got
```
N atoms:  2822
N residues 157
Residue names:  {'LIG', '0C9'}
N LIG atoms:  14
N 0C9 atoms:  0
```
Here is the `prmtop` file to reproduce the problem: [SYSTEM.prmtop.zip](https://github.com/mdtraj/mdtraj/files/1786016/SYSTEM.prmtop.zip)

cc: @gduarter, choderalab/yank#891

**Comment by MauriceKarrenbrock** [comment]
Hello, I just encountered the same problem with a residue called 1XA

mdtraj version 1.9.5 from conda forge

the pdb file is attached:
[output.pdb.txt](https://github.com/mdtraj/mdtraj/files/6208320/output.pdb.txt)

Therefore I guess that the problem hasn't been solved and should be reopened

```
import mdtraj

a = mdtraj.load('output.pdb')

top = a.topology

topology.select('resname 1XA')
```
returns an empty array

**Comment by MauriceKarrenbrock** [comment]
I have done some tests an I have seen that if you put the resname quoted everything works OK
```
topology.select('resname "1XA"')
```
returns what expected.

I thing the problem is in the mdtraj/core/selection.py file at line 334 https://github.com/mdtraj/mdtraj/blob/0dde9a64563faeec742b563e25deea988edf3c70/mdtraj/core/selection.py#L334
```
literal = (
            ~(keywords(BinaryInfixOperand) | keywords(UnaryInfixOperand)) +
            (Word(NUMS) | quotedString | Word(alphas, alphanums))
        )
```

I don't really know how that kind of things work, but by trying to play around I found out that if I put  ```Word(alphanums, alphanums)``` before ```Word(NUMS)```

I get a syntaxerror 
```
E         File "<unknown>", line 1
E           1XA
E             ^
E       SyntaxError: unexpected EOF while parsing

/home/maurice/miniconda3/envs/mdtraj/lib/python3.7/ast.py:35: SyntaxError
```

and the test_element test in the selection tests file fails

```
E           AssertionError: "Compare(left=Attribute(value=Attribute(value=Name(id='atom', ctx=Load()), attr='element', ctx=Load()), attr='mass', ctx=Load()), ops=[In()], comparators=[List(elts=[Num(n=5), Num(n=0.5), Str(s='to'), Num(n=12), Num(n=0.3)], ctx=Load())])" != "Compare(left=Num(n=5.5), ops=[LtE(), LtE()], comparators=[Attribute(value=Attribute(value=Name(id='atom', ctx=Load()), attr='element', ctx=Load()), attr='mass', ctx=Load()), Num(n=12.3)])"

mdtraj/testing/testing.py:79: AssertionError
```
While if I add a ```Word(NUMS, alphanums)``` at the end of the line nothing changes.

There must be a way to make the select function recognize a word that starts with a number without needing to quote it, I guess?
