### ISSUE TITLE
Time in .DCD files

### ISSUE THREAD

**Issue by padix-key** [mdtraj/mdtraj#1436]
The documentation of `mdtraj.load_dcd()` states, that .DCD files contain time information, but the `DCDTrajectoryFile.read()` method does only return `xyz`, `cell_lengths` and `cell_angles`.
Is there way to extract the time information via the `DCDTrajectoryFile` class?

**Comment by marscher** [comment]
The method read_as_traj should return the time information.

**Comment by padix-key** [comment]
To my understanding, the time information provided by `read_as_traj()` is the frame number instead of the actual simulation time. Here an excerpt of `dcd.pyx`:
``` python
if stride is None:
    stride = 1
time = (stride*np.arange(len(xyz))) + initial
```
with `inital` being
``` python
initial = self.tell()
```

**Comment by marscher** [comment]
You're right, the time is not being read by the vmd plugin. We need to change the api of the read method to return the time.
@mdtraj/developers Do you think it would hurt anybody if DCDTrajectoryFile.read returns 4 values instead of 3? I mean it would break peoples code, if the rely on the read method. In addition most files do not provide time information, so the time array is zero after all, how should we treat that?

@padix-key You can use this branch, which will return the physical time: https://github.com/marscher/mdtraj/tree/dcd_read_phys_time

**Comment by padix-key** [comment]
Thank you. I would appreciate, if this was added into the official repository, as I am writing a library that depends on *MDTraj* for reading/writing trajectories. I think it is a bit inconsistent that `DCDTrajectoryFile.read()` does not return the simulation time.

**Comment by marscher** [comment]
On 08.03.19 14:16, Patrick Kunzmann wrote:
> Thank you. I would appreciate, if this was added into the official repository, as I am writing a library that depends on *MDTraj* for reading/writing trajectories. I think it is a bit inconsistent that `DCDTrajectoryFile.read()` does not return the simulation time.
> 

could you please test this branch, as I'm lacking trajectory data, which 
contains meaningful time information?

**Comment by padix-key** [comment]
Unfortunately `DCDTrajectoryFile.write()` does still not support giving the simulation time. The trajectory data I have is currently in TRR and XTC formats. Hence, I cannot create DCD files with meaningful time data

**Comment by marscher** [comment]
the write method of the plugin implementation does not allow to write custom time information. I do not have the time to dig deeper into this. Actually the storage of a (constant) time delta between the steps should be sufficient, right?

**Comment by padix-key** [comment]
I think so.
