### ISSUE TITLE
Unpredictable segmentation faults with compute_dssp()

### ISSUE THREAD

**Issue by SBolo** [mdtraj/mdtraj#1473]
Hi everyone,
I'm running the function `compute_dssp()` on a set of proteins. This is the very simple snippet I'm using to use dssp only on the 0th chain of every pdb:
```
import glob
import mdtraj as md

pdbs = glob.glob("my_proteins/*.pdb")

for i,p in enumerate(pdbs):
    
    print(i)
    struct = md.load( p )
    top = struct.topology
    chain0 =  struct.atom_slice( top.select('chainid 0') )
    print(chain0)

    dssp = md.compute_dssp( chain0 )
```

Now, what happens is that, in a totally unpredictable way, the script segmentation faults when computing dssp. I mean that the segmentation fault always happens with a different protein and, if I try to analyze that particular protein separately outside the loop, no errors occur.  `chain0`, `struct` and `top` have always a non-zero number of residues and atoms when the segmentation fault happens. Can you help understand what is going on here?

**Comment by justinrporter** [comment]
I had a problem like this a while ago, and I wound up compiling mdtraj with [debug symbols](https://cython.readthedocs.io/en/latest/src/userguide/debugging.html) and running my [script under gdb](https://wiki.python.org/moin/DebuggingWithGdb) to figure out where the problem was.

That's pretty involved, so maybe somebody else has a better idea?

**Comment by rmcgibbo** [comment]
yeah, i'd definitely run under gdb to get a backtrace.

**Comment by rmcgibbo** [comment]
does the same issue happen if you don't slice the protein down to chain0?

**Comment by SBolo** [comment]
Yes it does. I tried with the full pdb and the issue remains. The odd thing is that it seems to happen randomly, because if I restart the calculation from the protein that caused the segmentation fault, everything runs fine for a while.

**Comment by rmcgibbo** [comment]
> The odd thing is that it seems to happen randomly.
This is fairly common for segfaults. There's probably an out-of-bounds memory access and given ASLR and stuff, it's different on each invocation.

**Comment by rmcgibbo** [comment]
I have a few more questions:
1. Can you reproduce the segfault using .pdb files that are in the `tests/data/` directory (that would be ideal), or otherwise easily accessible (slightly less ideal)?
2. How did you install mdtraj (conda, pip, etc)? What operating system are you on? If compiled yourself, what compiler? What version of python?

So far, I just tried this on Linux (python 3.7.1, gcc 7.4)
```
import mdtraj 
for i in range(100): 
    t = mdtraj.load("data/2EQQ.pdb")   # from https://github.com/mdtraj/mdtraj/tree/master/tests/data
    mdtraj.compute_dssp(t) 
```
and have not been able to get it to crash.
