### ISSUE TITLE
hbond functions not finding hbonds for particular trajectory

### ISSUE THREAD

**Issue by nffaruk** [mdtraj/mdtraj#1510]
Hi, I'm trying to reproduce the hydrogen bonding map of [Figure 2 of this paper](https://doi.org/10.7554/eLife.26526.005). However, loading the trajectory provided in the [supplementary files](https://doi.org/10.7554/eLife.26526.024) using the included .gro topology and calling wernet_nilsson() or baker_hubbard() on it returns no hbonds. VMD's HBonds plugin is able to find them.

**Comment by PomesLaboratory** [comment]
Hey @nffaruk , have you tried loading (md.load) your trajectory files with a .pdb toplogy file? 

After looking into the core topology file, it seems that the initial bonds are created by reading some .pdb standard bond definitions. 

(FYI, I found this information in the mdtraj/core/topology.py script under the "create_standard_bonds" method)

I hope this helps!

Best,
Richard Banh

**Comment by banhrich** [comment]
Hey @nffaruk , have you tried loading (md.load) your trajectory files with a .pdb toplogy file?

After looking into the core topology file, it seems that the initial bonds are created by reading some .pdb standard bond definitions.

(FYI, I found this information in the mdtraj/core/topology.py script under the "create_standard_bonds" method)

I hope this helps!

Best,
Richard Banh

**Comment by nffaruk** [comment]
@banhrich that seems to have fixed it - saving a frame as a .pdb and using that as the topology. However, I think that either the missing info should be generated automatically or there should be an additional error message (right now the hbond functions just check for the presence of a topology, eg. [here](https://github.com/mdtraj/mdtraj/blob/f80d885d374a357a7badeefafc0d331de617bd52/mdtraj/geometry/hbond.py#L227-L229))

**Comment by banhrich** [comment]
Glad to hear it worked! I agree 100%. I've submitted 2 change requests:
1. Create the bonds list when loading a .gro file [[here](https://github.com/mdtraj/mdtraj/compare/master...banhrich:patch-1?expand=1)].
2. A quick check to see that topology.bonds > 0 in order to properly run the wernet_nilsson() or baker_hubbard() functions. Otherwise, it will raise an error message (the error message can be more concise and descriptive though). [[here]](https://github.com/mdtraj/mdtraj/compare/master...banhrich:patch-2?expand=1)

Hopefully the suggested changes get implemented in some way or addressed in feature releases.

**Comment by nffaruk** [comment]
Awesome, I hope that they are implemented. I'll keep this issue open till then.

**Comment by rmcgibbo** [comment]
@banhrich I'm not sure that those have been opened as pull requests actually.

**Comment by banhrich** [comment]
@rmcgibbo Thanks for the heads up! I think they should be open now.

**Comment by rmcgibbo** [comment]
great, thanks. i'll merge them once the tests pass. both look totally reasonable.
