### ISSUE TITLE
Issue with mdt.formats.PDBTrajectoryFile

### ISSUE THREAD

**Issue by jacknicoludis** [mdtraj/mdtraj#1540]
I have some C-alpha coordinates that I got from a trajectory that I extract with .xyz and then manipulate and then save with the original topology file and the output pdb file does not contain all of the atoms of the xyz object or the topology. 

```
print(new_xyz.shape)
print(trj.top)
new_pdb = mdt.formats.PDBTrajectoryFile(new_pdb_filename, mode='w', force_overwrite=True)
new_pdb.write(new_xyz,trj.top)
new_pdb_load = mdt.load(new_pdb_filename)
print(new_pdb_load)
```
Returns:
```
(1829, 3)
<mdtraj.Topology with 1 chains, 1829 residues, 1829 atoms, 0 bonds>
<mdtraj.Trajectory with 1 frames, 1734 atoms, 1734 residues, without unitcells>
```

I have no idea where this 1734 number comes from as nothing else I'm doing has this number of atoms. Looking at the sequence, it is just truncating the last 95 residues, but I don't know why. Any help?

(Same error happens if I use `mdt.load_pdb()` instead of `mdt.load()`)

**Comment by justinrporter** [comment]
I don't know too much about that area of the code, but it might be helpful to someone who does if you attach the PDB you're using? Or, even better, a reduced PDB that demonstrates the problem without having nearly 2000 residues. :)

**Comment by jacknicoludis** [comment]
I tried with a new (smaller) pdb and had the same problem (though different number of atom differences).
```
test_pdb = mdt.load_pdb('6meq.pdb')
test_CAs = test_pdb.topology.select("name CA") #make a selection of the CA atom number
pdb_CAs = test_pdb.atom_slice(test_CAs)
print(pdb_CAs)
mean_pdb = mdt.formats.PDBTrajectoryFile('6meq_new.pdb', mode='w', force_overwrite=True) #open a PDB format file
print(pdb_CAs.xyz.shape)
print(pdb_CAs.top)
mean_pdb.write(pdb_CAs.xyz[0],pdb_CAs.top) #save mean CA coordinates
new_pdb = mdt.load('6meq_new.pdb')
print(new_pdb)
```

Returns:

```
<mdtraj.Trajectory with 1 frames, 425 atoms, 425 residues, and unitcells>
(1, 425, 3)
<mdtraj.Topology with 2 chains, 425 residues, 425 atoms, 0 bonds>
<mdtraj.Trajectory with 1 frames, 408 atoms, 408 residues, without unitcells>
```

I used the pdb 6meq from RCSB.

**Comment by jacknicoludis** [comment]
Using the `mdt.formats.GroTrajectoryFile` or `mdt.formats.XYZTrajectoryFile` methods worked, so there must be an issue with the `mdt.formats.PDBTrajectoryFile` method

**Comment by rmcgibbo** [comment]
That's pretty weird. I have no idea.

**Comment by atharva-kelkar** [comment]
Reopening this issue since it is popping up even in my codes -

Specifically, when I try to use the Trajectory.save_pdb method, the save does not capture all bonds. Sample code shown below - 
```
# traj is an MDTraj trajectory object
for bond in traj.topology.bonds: 
    print(bond[0].index, bond[1].index)
```

gives the following output:
```
0 1
1 2
2 3
4 5
2 4
```

However, when I save the PDB file, using `traj.save_pdb(file_name)`, the PDB file contains only 2 unique bonds instead of 5 (see image below). This could be a problem of residue names but I don't see why it should be like this if my bond indices are stored correctly in the MDTraj topology object. Please let me know if someone knows a workaround or if this is an open issue.

![image](https://user-images.githubusercontent.com/44296029/143874203-6e75a800-ed15-49c9-84a1-0d520a41b088.png)
