### ISSUE TITLE
modified compute_contacts and LGPL v2.1

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1569]
Hi guys, 

I have a modified md.compute_contacts that also returns the indices of the closest atom pairs. It allows me to distinguish backbone from sidechain interactions further down the analysis pipeline. It's a minor modification on your code. You can check it out here:

https://github.com/mdtraj/mdtraj/compare/master...gph82:return_atom_pairs?expand=1

Now, for a software project that I am working on, I would like to use and distribute that modified version (just of compute_contacts), but I don't know whether the LGPL v2.1 version allows for it (I would use the appropriate license, attribution etc). The following overview mentions that the modified version "must also be a library"

> Licensees may modify an LGPL-licensed library, but if they wish to distribute their modified version it must also be a library. Modifications to LGPL-licensed libraries should not impair the library’s ability to work with a wide range of programs

(from http://oss-watch.ac.uk/resources/lgpl)

What options are there to do this (if any)? BTW the code uses mdtraj normally, it is declared as dependency in setup.py

Any thoughts or suggestions would be very welcome, I am a bit out of my depth regarding these license issues.

Thanks in advance!

**Comment by rmcgibbo** [comment]
Hi Guillermo!

My understanding of the licensing stuff is basically as follows:

* If you modify MDTraj and then use your modified copy of MDTraj in some released project, you should distribute your modifications to MDTraj under the LGPL as well or a compatible license (or GPL, maybe others).
* If you just _use_ MDTraj in your own project without modifying it, then you get to do whatever you like (you could distribute your own project under any open-source license or keep it proprietary, etc).

The idea here, at least to me, is that people can (1) use and modify MDTraj in their internal projects without limitation; (2) use un-modified MDTraj in their projects that they release to users, even if it's an otherwise closed-source project, but that (3) if they modify MDTraj and use a modified version of MDTraj in a project that they release to users, they need to open-source their modifications to MDTraj.

Since your modifications are available at https://github.com/gph82/mdtraj (and the LICENSE file there says "LGPL"), I think you've fulfilled your obligations. You're fine. The key use-case that the license is trying to prevent is the case in which some company makes modifications to MDTraj, uses those modifications in a non-LGPL (e.g., proprietary) product that they release to the public, and then don't open-source their modifications to MDTraj back to the community.

(Disclaimer: I'm not a lawyer. This is not legal advice.)

**Comment by gph82** [comment]
Hi Robert,

thanks very much answering.  I've been doing some reading here:
 * https://www.oreilly.com/library/view/understanding-open-source/0596005814/ch03.html
 * https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)
 * http://oss-watch.ac.uk/resources/lgpl
 * https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

and am now a better informed. I think (I am not a lawyer either) that the license type allows what I want. My module itself would be LGPLv3, BTW.

Still, there's this notion that I have to re-publish my modified mdtraj fully (prominently stating original authors, the changes etc) and then make my module depend on that. My core question/issue is that I cannot simply Ctrl+C Ctr+V **the one method** that I am modifying and ship just it e.g. in a  `mod_md_compute_contacts.py` file with the attributions, modifications etc there. 

I need to find out if that is, indeed, not allowed, before I do the re-publish of all of mdtraj. 

Obviously, this would all get much simpler if you decided to include this behavior in mdtraj itself, but I highly doubt that's an option, right? An optarg "return_atoms = False" wouldn't break the API. I thought for a second of preparing a PR but decided to ask the question first.

**Comment by rmcgibbo** [comment]
I think you can definitely just Ctrl-C Ctrl-V the one method that you're modifying and shit it. As long as your `mod_md_compute_contacts.py` is LGPL too, you're in the clear. At it being on github is sufficient to "re-publish", you don't have to do anything fancy.

**Comment by gph82** [comment]
Thanks very much for the quick answer! Yes, that would be my preferred way. I'll keep you guys posted, feel free to close this issue!

**Comment by rmcgibbo** [comment]
:+1:

**Comment by peastman** [comment]
Do make sure you include the original copyright notice at the top of your modified version of the method so people know where it came from and who wrote the original version.

**Comment by gph82** [comment]
Of course, absolutely, that goes without saying



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
