### ISSUE TITLE
The website mdtraj.org is down

### ISSUE THREAD

**Issue by ixdi** [mdtraj/mdtraj#1593]
Hi, It's not possible to access the web mdtraj.org. IP access error

Thanks

**Comment by mattwthompson** [comment]
Thanks for the report. This is probably due to some AWS bill not being paid, similar to the current status of openmm.org and omnia.md. It looks like the account has since been paid, so maybe it will come back online soon. See this thread for more: https://github.com/openmm/openmm/issues/2824#issuecomment-719121448

**Comment by peastman** [comment]
Is it still hosted on the Pande lab account?  If so, that account will be going away very soon, so you need to move it somewhere else.

**Comment by rmcgibbo** [comment]
Well that's annoying.

**Comment by rmcgibbo** [comment]
Once the account is unlocked (https://github.com/openmm/openmm/issues/2824#issuecomment-719121448), I will move the content to my personal AWS account, I suppose.

**Comment by jchodera** [comment]
Quick update: The issue was that the invoices had been going to a deactivated account at Stanford and nobody noticed. The account was suspended after four months of non-payment by Stanford.

Stanford is working on paying the invoices, and I've asked for a status update on when to expect this. If it's longer than a couple of days, I'll see about settling the account myself to get things reactivated.

**Comment by rmcgibbo** [comment]
Thanks, John. I got the mdtraj.org domain name transferred to my godaddy, so I should be able to redirect the nameservers to my own AWS. That should let me serve the mdtraj docs from the website, since I can just build them fresh. In terms of getting the docs for the older MDTraj releases, it'll probably be easier to pull them off the old AWS account than to try to rebuild them, but it's not _urgent_ to have the docs for old releases of the code up.

But I just haven't done that yet.

**Comment by jchodera** [comment]
> Thanks, John. I got the mdtraj.org domain name transferred to my godaddy, so I should be able to redirect the nameservers to my own AWS

If you can figure out how to do that, please let me know! I've had openmm.org transferred, but it seems like the AWS DNS servers (which are currently refusing to serve the IP) have to first relinquish control.

> In terms of getting the docs for the older MDTraj releases, it'll probably be easier to pull them off the old AWS account than to try to rebuild them, but it's not urgent to have the docs for old releases of the code up.

The hold on payment should be released today, according to Stanford, which hopefully means things will be processed tomorrow.
Will update as I have more info.

**Comment by ixdi** [comment]
Meanwhile if someone wants to view documentation go to docs folder and execute
```sh
cd docs
mkdir _build
make html
```
A _build/html folder with an index.html will be created.

**Comment by rmcgibbo** [comment]
The website should be back up now, containing just the docs for the 1.9.4 release.
