### ISSUE TITLE
Unable to import mdtraj after installation with conda

### ISSUE THREAD

**Issue by Dr-Zully** [mdtraj/mdtraj#1608]
I followed the guidelines on the installation of mdtraj using conda. Although the latest version of Anaconda is installed on my computer, I created an environment with python version 3.5 and proceeded to install mdtrag. However I couldn't import it on jupyter notebook. Here's the iwhat I obtained after running the code; 

ValueError                                Traceback (most recent call last)
<ipython-input-1-bd5f77d5c4e6> in <module>()
----> 1 import mdtraj

~/anaconda3/lib/python3.7/site-packages/mdtraj/__init__.py in <module>()
     28 import numpy as _  # silence cython related numpy warnings, see github.com/numpy/numpy/pull/432
     29 
---> 30 from .formats.registry import FormatRegistry
     31 from .formats.xtc import load_xtc
     32 from .formats.trr import load_trr

~/anaconda3/lib/python3.7/site-packages/mdtraj/formats/__init__.py in <module>()
      2 
      3 from .arc import ArcTrajectoryFile
----> 4 from .dcd import DCDTrajectoryFile
      5 from .binpos import BINPOSTrajectoryFile
      6 from .xtc import XTCTrajectoryFile

mdtraj/formats/dcd/dcd.pyx in init mdtraj.formats.dcd()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by mattwthompson** [comment]
If at all possible, I recommend upgrading to a newer Python version, at least 3.6 but preferably 3.7 or 3.8.

**Comment by rmcgibbo** [comment]
@Dr-Zully: This means that the version of numpy you're using is incompatible for some reason with the version of mdtraj you have. This could be because the mdtraj conda package was constructed incorrectly. Or it could be something inconsistent in your environment, like using a mixture of conda install and pip install in the same env.

You could try to make a new conda env to test the later hypothesis.

But we're not developing packages for python3.5 anymore. If you're installing mdtraj using conda, you must be pulling in a very old version of mdtraj, since we haven't built python3.5 packages in >2 years.
