### ISSUE TITLE
PIP package numpy incompatibility

### ISSUE THREAD

**Issue by InnocentBug** [mdtraj/mdtraj#1617]
We are having trouble the binary incompatibility with mdtraj as pulled with pip.
I am reporting the details from a Ubuntu20.04 docker container as this is probably the cleanest environment.
The python version is 3.8 and the mdtraj version pulled is 1.9.5

Installing `mdtraj` with pip and using it to write trajectories with the HDF5 Reporter results in this import error"
```
Traceback (most recent call last):
  File "bulk_npt.py", line 10, in <module>
    from mdtraj.reporters import HDF5Reporter  # pylint: disable=import-error
  File "/home/ludwigschneider/.local/lib/python3.7/site-packages/mdtraj-1.9.5-py3.7-linux-x86_64.egg/mdtraj/__init__.py", line 30, in <module>
    from .formats.registry import FormatRegistry
  File "/home/ludwigschneider/.local/lib/python3.7/site-packages/mdtraj-1.9.5-py3.7-linux-x86_64.egg/mdtraj/formats/__init__.py", line 4, in <module>
    from .dcd import DCDTrajectoryFile
  File "mdtraj/formats/dcd/dcd.pyx", line 1, in init mdtraj.formats.dcd
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
Manually requesting the numpy version `1.16.5` and requesting manually `pytables` seems to fix these problems.

Is there a possibility to get a pip install that works with newer versions of numpy?

**Comment by InnocentBug** [comment]
The problem might be related to #1608 but it is a different installation method and a newer python version here.

**Comment by rmcgibbo** [comment]
Sorry, I'm not sure what the issue is here. You might have better luck using `conda` or installing mdtraj from source using pip's `--no-binary=mdtraj` (or something of that sort, untested) flag.

**Comment by mattwthompson** [comment]
What version of `numpy` is installed at first? I just did a fresh pull on a Ubuntu 20.04 VM and 1.20 is pulled down. I didn't run the full test suite but `from mdtraj.reporters import HDF5Reporter`  runs without this error.

Generally +1 to conda > pip for these sorts of things

**Comment by InnocentBug** [comment]
Thanks for looking into this.

**Comment by InnocentBug** [comment]
Without specifying a version of numpy. My installation pulls version 17.4 for numpy.

**Comment by InnocentBug** [comment]
> Generally +1 to conda > pip for these sorts of things
Our project cannont use anaconda (too large, too unwielding, too many other python packages we are relying on.)

**Comment by sroet** [comment]
> Sorry, I'm not sure what the issue is here. 

@rmcgibbo  The issue here is that mdtraj is compiled (in build isolation) against the most recent version of `numpy` (`1.20.0`) when `pip` installed. Similar to #1446 , luckily [the same fix](https://github.com/mdtraj/mdtraj/issues/1446#issuecomment-490553762) works.

Just in case people want to install `mdtraj` via `pip`, but don't want to upgrade to the latest `numpy`, running:

```
pip install --no-use-pep517 mdtraj
``` 
will compile `mdtraj` with whatever `numpy` and `cython`is currently present on your system. 

As that option indicates, it goes against [`pep517`](https://www.python.org/dev/peps/pep-0517/) and should **only** be used if you have a ***very* good reason** not to upgrade dependencies like `numpy`. (I only use it for CI where I explicitly run the test suite on the minimal versions of the dependencies to notify me if/when I need to update these minimum versions)

A command  to reinstall a `mdtraj` that is broken in this way is a bit tricky due to `pip` caching and can be done by the following command:
```
pip install --force-reinstall --no-binary mdtraj --no-deps --no-use-pep517 --no-cache-dir mdtraj
```
Please make sure you understand what this code is doing before running (as with any code you find on the internet), you can read up on these options with `pip help install`. This only works if `numpy` and `cython` are already installed and present.

**Comment by rmcgibbo** [comment]
@sroet: Do you know if it's possible for us to either pin numpy to a lower version during the build or set the install_requires metadata to be ">= the version used during the build", while still staying in pep517 mode?

**Comment by InnocentBug** [comment]
@sroet thanks for the in-depth explanation.

**Comment by rmcgibbo** [comment]
Perhaps this is possible -- pin numpy to an older version inside a particular place in pyproject.toml: https://github.com/rgommers/scipy/blob/master/pyproject.toml#L7

**Comment by sroet** [comment]
> Perhaps this is possible -- pin numpy to an older version inside a particular place in pyproject.toml: https://github.com/rgommers/scipy/blob/master/pyproject.toml#L7

I was working through something similar and that indeed works as expected, `numpy` is generally forward compatible ( I tried pinning it to `1.16.5` in the build, with `1.20` in the running environment. ) The only issue I ran into was that `numpy==1.6` (my first try)  was not resolvable for `python=3.7`, but it seems that the way scipy does it is indeed how it is supposed to be used.

**Comment by sroet** [comment]
Having a quick look on pypi the minimal numpy versions (with the latest bugfix release) for each python version are:
```
"numpy==1.6.2; python_version=='2.7'",
"numpy==1.6.2; python_version=='3.2'",
"numpy==1.7.2; python_version=='3.3'",
"numpy==1.7.2; python_version=='3.4'",
"numpy==1.9.3; python_version=='3.5'",
"numpy==1.11.3; python_version=='3.6'",
"numpy==1.14.6; python_version=='3.7'",
"numpy==1.17.5; python_version=='3.8'",
"numpy==1.19.5; python_version=='3.9'",
"numpy; python_version>='3.10'"
```
Now you might want to start following [`NEP29`](https://numpy.org/neps/nep-0029-deprecation_policy.html)
which would alter this to:
```
"numpy==1.17.5; python_version=='3.7'",
"numpy==1.17.5; python_version=='3.8'",
"numpy==1.19.5; python_version=='3.9'",
"numpy; python_version>='3.10'"
 ```
