### ISSUE TITLE
compute_displacement_t function

### ISSUE THREAD

**Issue by VietNguyen120195** [mdtraj/mdtraj#1662]
I saw that we have compute_distance and compute_distance_t methods but not compute_displacement_t function. Can you further implement this function?.

**Comment by mattwthompson** [comment]
We implemented the functions we did because that's what we needed for a particular study. I'm not familiar with computing displacements since it's not something I came across in grad school. I would expect that implementing `compute_displacements_t` would follow a similar structure as `compute_distance_t` and somebody could use https://github.com/mdtraj/mdtraj/pull/1633 as a guide for doing that.
