### ISSUE TITLE
Remove or update TNG module

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1788]
The tests involving a TNG format (which I had not heard of before today) are failing on macOS:

```
FAILED tests/test_tng.py::test_load_topology - ValueError: This file does not contain topology information, and no Topology was provided.
```

But these run fine on my machine:

```
(py311) [mdtraj] pytest tests/test_tng.py                                                                          21:22:36  ☁  py311 ☀
========================================================= test session starts ==========================================================
platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0 -- /Users/mattthompson/mambaforge/envs/py311/bin/python3.11
cachedir: .pytest_cache
rootdir: /Users/mattthompson/software/mdtraj, configfile: pytest.ini
plugins: xdist-3.0.2
collected 3 items

tests/test_tng.py::test_load_trajectory PASSED                                                                                   [ 33%]
tests/test_tng.py::test_load_topology PASSED                                                                                     [ 66%]
tests/test_tng.py::test_write PASSED                                                                                             [100%]

=========================================================== warnings summary ===========================================================
../../mambaforge/envs/py311/lib/python3.11/site-packages/mdtraj/formats/__init__.py:6
  /Users/mattthompson/mambaforge/envs/py311/lib/python3.11/site-packages/mdtraj/formats/__init__.py:6: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
    from .xtc import XTCTrajectoryFile

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================== 3 passed, 1 warning in 0.90s =====================================================
(py311) [mdtraj]                                                                                                   21:22:42  ☁  py311 ☀
```

@peastman I see your name in a lot of `formats/tng/` files - any idea what might be going on here? I _think_ `mdtraj/formats/tng/tng.pyx` should be re-cythonized in these builds, though not tracked in the git tree. The imports in this file don't give much of a hint as to what might have changed in the new Python version.

_Originally posted by @mattwthompson in https://github.com/mdtraj/mdtraj/issues/1758#issuecomment-1304699462_

**Comment by peastman** [comment]
It's been a very long time since I did anything with that code.  TNG files are a bit unusual in that they *can* store topology information, but they don't have to.  You can provide a topology when you load it, or you can use the information from the file.  But if the information isn't there, and you don't provide a topology, you get an exception.

More specifically, here's where it tries to load it in the TNGTrajectoryFile constructor.

https://github.com/mdtraj/mdtraj/blob/dc22ce84e91a9c31499b3d13d41479b714099c01/mdtraj/formats/tng/tng.pyx#L295

And here's where it decides which one to use.

https://github.com/mdtraj/mdtraj/blob/dc22ce84e91a9c31499b3d13d41479b714099c01/mdtraj/formats/tng/tng.pyx#L470-L473

**Comment by mattwthompson** [comment]
Whoops, sorry for the repeated ping there. I didn't consider that would happen when using the "Reference in a new issue" drop-down.

Thanks for the information!

**Comment by mattwthompson** [comment]
I heard through the grapevine that this file format is (at least) deprecated. I don't think it's used much, and I'm using that as justification to suggest dropping. It's also causing some [build issues](https://github.com/conda-forge/mdtraj-feedstock/pull/52#issuecomment-1814789302) over in `conda-build` world.

I won't have time to do it for a few days, but I bet we'd welcome a PR that just removes these files, tests, related docs if they exist, etc. etc.

**Comment by sukritsingh** [comment]
I've never generated any trajectories in the TNG format myself (nor have I interacted with it in recent history), so I think if it's deprecated already then I'm totally in support with dropping support for the TNG format as well!

**Comment by sukritsingh** [comment]
Just so we have it in writing: Is there any kind of written announcement that TNG is deprecated that we can reference? Mainly my question is – Is TNG format used anywhere? If so, then it could be worth updating the files/code to the newest version.

If it's not even being used at all, and we have a written declaration of deprecation, I'm not entirely convinced it's worth the effort in updating code + testing for compatibility with a deprecated format (or the update is a low priority effort)

**Comment by sukritsingh** [comment]
Given the lack of hearing about TNG usage, I agree that it's a bigger priority that we ensure that the macOS build works also. 

Since we have the option for trying out the most recent changes, but we aren't sure what the level of usage/support is, how do we feel about the following "quick try":

1. Grab the recent changes, give them a whirl here, and see if that fixes the build issues as well
2. If the build issues remain unresolved because of TNG compatibility, we remove TNG support altogether until we can debug the issue. 

Open to modifications to this proposal!

**Comment by mattwthompson** [comment]
To make things easier, I'm deciding now to just remove the TNG module. This issue has been open (and public) for a few months now without anybody clamoring to keep it around nor anybody mentioning that they actually use it.

If this later demonstrates itself to be a mistake, it's easy to revert the removal of files, so I anticipate it's not a committal change.

**Comment by mattwthompson** [comment]
I removed it. If anybody wishes to add it back, there should be a paper trail here to get started.
