### ISSUE TITLE
Seemingly stochastic "UNCONVERGED ROTATION MATRIX. RETURNING IDENTITY=300" error when using mdtraj.Trajectory.superpose()

### ISSUE THREAD

**Issue by glass-w** [mdtraj/mdtraj#1798]
I have a set of trajectories that are all of the same system (protein + ligand) and have each been started from a random seed. As part of my analysis I image and align these trajectories using `mdtraj.Trajectory.superpose()`. For some of these trajectories I kept seeing `UNCONVERGED ROTATION MATRIX. RETURNING IDENTITY=300` that seems to come from [this line](https://github.com/mdtraj/mdtraj/blob/1.9.8/mdtraj/rmsd/src/theobald_rmsd.cpp#L300).

General steps taken for alignment:

```python

ref = md.load("example.rst7", top="example.prm7")
traj = md.load("example.nc", top="example.prm7")
(lig,) = [x for x in traj.topology.residues if "LIG" in x.name]
traj.image_molecules(inplace=True, anchor_molecules=[lig.atoms])

atom_indices = find_atom_indices() # custom function, returns a 1D NumPy array
traj.superpose(ref, atom_indices=sele)
```

Steps I have tried to investigate this:

- Run the alignment again on the trajectories that failed.
    - On the first attempt they all passed.
    - I ran a second time, this time aligning only one of the failed trajectories but repeated the alignment 20 times, three failed and the rest passed.
- Visually inspect the trajectories: all pre-aligned trajectories look correct, when an alignment succeeds the trajectory also looks correct and is aligned as expected.

Additionally, this issue is coming up in other simulated systems so it is unlikely to be an issue with system input.

Architecture details:
- `python=3.8`
- `mdtraj=1.9.8`
- OS="Amazon Linux 2"

**Comment by sukritsingh** [comment]
Unfortunately every system I've tried it on here can't seem to replicate this issue - do you have any system specific features you can highlight that are causing this problem? Or any files you can share to replicate this issue?

If it passed on the "failed" files in the first attempt, then it may be that there's some numerical weirdness around the rotation matrix computation. Does this convergence issue arise regardless of which atoms you use in `superpose`?

**Comment by reedharrison** [comment]
I also ran into a similar issue when trying to superpose a trajectory, but changing the atom selections doesn't seem to help. Or at least I haven't found a selection that works. Not all frames of the trajectory have this problem, however.

If I superpose the last frame of the trajectory onto the first frame of the trajectory, there is no issue. However, if I superpose the first frame of the trajectory onto the last frame of trajectory, then the result contains atoms where all XYZ coordinates are identical and the following error is returned:
`mdtraj/rmsd/src/theobald_rmsd.cpp UNCONVERGED ROTATION MATRIX. RETURNING IDENTITY=296`

python=3.9
mdtraj=1.9.7
os=RHEL 8.7

Can start a separate issue if you think this is unrelated.

**Comment by sukritsingh** [comment]
Could you elaborate a bit more or provide an example file/code snippet? I'm having some trouble replicating this issue with any of the files I have. It sounds like you are able to load in to MDTraj `Trajectory` objects fine, and I would superpose them like this: 
```
# Load in two structures
struc = md.load("structure1.pdb")
struc2 = md.load("structure2.pdb")

# define selection atoms 
strucAtoms = struc.top.select("backbone")
struc2Atoms =struc2.top.select("backbone")

# superpose A to B and then B to A
struc.superpose(struc2, 0, strucAtoms, struc2Atoms)
struc2.superpose(struc, 0, struc2Atoms, strucAtoms)
```

Both of the two `superpose` commands work without returning any errors as long as the right number/set of atoms are chosen.

**Comment by reedharrison** [comment]
I can provide a test case if you want, but it seems to me that the issue was some very mobile atoms sneaking into the atom selection. It would be nice if the superpose method returned raised an error instead of returning incorrect results, but I think it is relatively minor. Not sure if something similar happened for @glass-w

**Comment by sukritsingh** [comment]
> it seems to me that the issue was some very mobile atoms sneaking into the atom selection

Possibly but if that's the case then wouldn't removing those atoms (ie choosing a more rigid set of atoms in the selection) alleviate this issue? It sounds like that wasn't necessarily the case here but I may be misunderstanding.

We could consider editing it to throw an error instead of returning the same XYZ results for sure, but I think ultimately this should be a rare issue anyways only coming up when you're identifying an appropriate atom selection to align on, no?

**Comment by reedharrison** [comment]
Yes, removing the atoms fixed the problem for me. At first I thought it did not, but I could not reproduce that behavior later. Perhaps that was because the Trajectory object was already incorrect and I forgot to reload it.

And I think it should be rare, but occasionally I won't even get the "mdtraj/rmsd/src/theobald_rmsd.cpp UNCONVERGED ROTATION MATRIX. RETURNING IDENTITY=296" warning. I can just check to see if atoms have been superposed on a single point, though.

My problem may also be slightly different from the original issue.

**Comment by sukritsingh** [comment]
Was any resolution achieved here? In general I tend to avoid using less mobile atoms at the termini for these calculations, and I was never able to replicate this issue with any of my systems?

**Comment by glass-w** [comment]
@sukritsingh this issue seemed to be stochastic and we haven't seen it since for other systems so it could have just been system specific. I'm happy to close this issue and reopen in the future if seen again. Thank you for looking into this.
