### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 

### ISSUE THREAD

**Issue by inefable12** [mdtraj/mdtraj#1808]
MDtraj doesn't recognize my system (Ligands + water + Na Cl + POPE, 310K, 50 ns) after executing in Jupyter Notebook:

traj = mdtraj.load_dtr('desmond_md_jesus103_trj/clickme.dtr',top='topology.pdb')
traj

The following error appears:

ValueError: invalid literal for int() with base 16: 'A1G '

**Comment by mattwthompson** [comment]
Could you share the full traceback, the version of MDTraj you're using, and the files that reproduce this error?

**Comment by jeremyleung521** [comment]
A little late but this error recently came to our attention. I believe it's due to the fact that the PDB topology file uses [Hybrid36 convention](https://cci.lbl.gov/hybrid_36/) when residue numbers/atom numbers overflow and `mdtraj.load` doesn't know how to deal with it. A "quick" fix would obviously be to use something other than a pdb file (or a pdb with the [HEX/VMD convention](https://github.com/openmm/openmm/issues/3501)) for topology. 

Looking at the GitHub history, someone already made a PR to fix this so I'm potentially thinking of reviving it, which will hopefully solve this! It was previously closed by the stale bot.
https://github.com/mdtraj/mdtraj/issues/906
https://github.com/mdtraj/mdtraj/pull/1675
