### ISSUE TITLE
mdtraj 1.9.9 and python 3.11.3

### ISSUE THREAD

**Issue by jdeckman** [mdtraj/mdtraj#1813]
Getting a segmentation fault in image_molecules with latest mdtraj using python 3.11:
`.../lib/python3.11/site-packages/mdtraj/core/trajectory.py:439: UserWarning: top= kwargs ignored since this file parser does not support it
warnings.warn('top= kwargs ignored since this file parser does not support it')
Fatal Python error: Segmentation fault 
Thread 0x00007fe6d8df9700 (most recent call first):
...
/lib/python3.11/site-packages/mdtraj/core/trajectory.py", line 2065 in image_molecules`

The same code runs fine with python 3.10

**Comment by mattwthompson** [comment]
See https://github.com/mdtraj/mdtraj/issues/1796 https://github.com/mdtraj/mdtraj/issues/1769

**Comment by jdeckman** [comment]
Thanks for the quick response. Yeah I've tried `image_molecules` with `inplace=True` and `inplace=False` but same result.

**Comment by CharlieLaughton** [comment]
With a fix that seems to solve issue #1769 (PR submitted), I get this behaviour with Python 3.11.3:

>>> t = mdt.load ('alanine-dipeptide-explicit.dcd', top='alanine-dipeptide-explicit.prmtop')
>>> print(t.xyz[0,0])
[1.352181  1.2696236 1.6946713]
>>> t2 = t.image_molecules(inplace=False)
>>> print(t2.xyz[0,0])
[nan nan nan]
>>> t3 = t.image_molecules(inplace=False, make_whole=False)
>>> print(t3.xyz[0,0])
[1.3557061 1.3241216 1.645923 ]
>>> t4 = t.make_molecules_whole(inplace=False)
>>> print(t4.xyz[0,0])
[1.352181  1.2696236 1.6946713]

So it seems the problem may be to do with how `image_molecules` plays with `make_molecules_whole` when the two processes are combined. Currently it seems that the code in `image_molecules()` with `make_whole=True` (the default), does not call `make_molecules_whole()` internally, but rather depends on the lower-level cython code (from `_geometry.image_molecules()`) to do the equivalent thing.

So it seems a work around is to replace:

```
t.image_molecules() # broken for Python 3.11
```

with:

```
t.make_molecules_whole()
t.image_molecules(make_whole=False)
```

But is this guaranteed to lead to exactly the same result in all cases? I'm not sure.

**Comment by jdeckman** [comment]
@CharlieLaughton Great, your workaround above works. Thanks a bunch!

**Comment by CharlieLaughton** [comment]
I've done some digging into mdtraj/geometry/src/image_molecules.pxi and think I've identified a couple of bugs that could be responsible for at least some of the behaviours people are seeing.

Firstly in `make_whole` there appear to be uninitialized variables:

```
cdef void make_whole(float[:,::1] frame_positions,
                float[:,::1] frame_unitcell_vectors,
                int32_t[:,:] sorted_bonds) nogil:
    # Fix each molecule to ensure the periodic boundary conditions are not
    # splitting it into pieces.
    cdef int atom1, atom2, j, k
    cdef float offset[3]
    cdef float delta[3]
    for j in range(sorted_bonds.shape[0]):
        atom1 = sorted_bonds[j, 0]
        atom2 = sorted_bonds[j, 1]
        for k in range(3):
            delta[k] = frame_positions[atom2, k]  - frame_positions[atom1, k]
            offset[k] = frame_unitcell_vectors[2, k]*roundf(delta[2]/frame_unitcell_vectors[2,2])
            offset[k] += frame_unitcell_vectors[1, k]*roundf((delta[1]-offset[1])/frame_unitcell_vectors[1,1])
            offset[k] += frame_unitcell_vectors[0, k]*roundf((delta[0]-offset[0])/frame_unitcell_vectors[0,0])
            frame_positions[atom2, k] = frame_positions[atom2, k] - offset[k]
```
The first time through the inner loop, there are references to delta[1], delta[2] and offset[1], none of which will have been initialized. Below, in `image_frame` we see similar code:

```
        delta = frame_positions[a2]-frame_positions[a1]
        offset = frame_unitcell_vectors[2]*np.round(delta[2]/frame_unitcell_vectors[2,2])
        offset += frame_unitcell_vectors[1]*np.round((delta[1]-offset[1])/frame_unitcell_vectors[1,1])
        offset += frame_unitcell_vectors[0]*np.round((delta[0]-offset[0])/frame_unitcell_vectors[0,0])
        for atom in anchor_molecules[next_anchor]:
            frame_positions[atom] -= offset
```
But there is a difference - here broadcasting rules mean offset[1] in line 3 has been initialized (line 2) before it is referenced.

If I edit the code in `make_whole` to match:
```
    for k in range(3):
            delta[k] = frame_positions[atom2, k]  - frame_positions[atom1, k]
    for k in range(3):
            offset[k] = frame_unitcell_vectors[2, k]*roundf(delta[2]/frame_unitcell_vectors[2,2])
    for k in range(3):
            offset[k] += frame_unitcell_vectors[1, k]*roundf((delta[1]-offset[1])/frame_unitcell_vectors[1,1])
    for k in range(3):
            offset[k] += frame_unitcell_vectors[0, k]*roundf((delta[0]-offset[0])/frame_unitcell_vectors[0,0])
            frame_positions[atom2, k] = frame_positions[atom2, k] - offset[k]
```
Then the 'nan' error seems to go away.

HOWEVER - the tests still fail with the segmentation violation error. More exactly, `test_image_molecules` fails at the point:
```
anchor_molecules = molecules[0:3]
t.image_molecules(inplace=True, anchor_molecules=anchor_molecules)
```
In my hands, `t.image_molecules` works fine as long as there is only one anchor molecule, but fails whenever there is more than one. After much digging, I think this is connected to the way the lists of anchor (and 'other') molecules are handled in some of the cython code - specifically as C++ vectors of memoryviews of numpy arrays ("cdef vector[int[:]] ..."). It appears there are issues with this - https://github.com/cython/cython/issues/3085.

I have therefore re-written sections of the code in `image_molecules.pxi` so that anchor (and "other") molecule data is passed differently: as a flat integer array of atom indices, and an array of pointers that identify where each molecule starts and ends within the indices array. In my hands this solves the problem, and all tests pass. There is a small performance hit - in cases where `image_molecules` was working before, the new code seems to run 10-15% slower - but of course it has the advantage of working in scenarios where the current code just crashes.

I'll submit a PR and then maybe someone else can take a look.

**Comment by CharlieLaughton** [comment]
Hi - just reminding folk there is a PR submitted for this - all feedback much appreciated.

**Comment by jeremyleung521** [comment]
I think this has been fixed in the recent releases. Please reopen if that's wrong!
