### ISSUE TITLE
How to micromamba (mistyped as minimamba, sorry) install release candidate?

### ISSUE THREAD

**Issue by hjuinj** [mdtraj/mdtraj#1889]
I would like to give the newest release candidate a try, when I tried to use the label indicated on this page https://anaconda.org/conda-forge/mdtraj to instal the rc via minimamba `conda install -c conda-forge conda-forge/label/mdtraj_rc::mdtraj` I get:
```
critical libmamba The package "conda-forge/label/mdtraj_rc::mdtraj" is not available for the specified platform
```

Just want to ask whether this is because I am using minimamba or this is an issue with the install instruction. Thank you

**Comment by mattwthompson** [comment]
Thanks for trying to install/test the RC

Hopefully you're asking about `micromamba` and not another project from Wulf and friends 😅

Does this command work? I was able to install it into one of my development environments for another project

```
$ micromamba install -c conda-forge -c conda-forge/label/mdtraj_rc "mdtraj >=1.10.0rc2"
```

A couple of things I noticed
* When listing multiple channels (with the CLI) you need to add `-c` for each
* I'm not sure this `channel_name/label/label_name::package_name` syntax works at the CLI ... though what you're using should work in YAML
* It might be useful to nudge it towards the specific version, otherwise a solver might avoid an "unstable" build

**Comment by hjuinj** [comment]
Thanks @mattwthompson, yeah and my bad :( I updated the title for people to correctly find this online. 
Thanks for the instruction, works like a charm!

**Comment by mattwthompson** [comment]
Great, let us know if you run into any issues
