### ISSUE TITLE
How to Adjust the Energy Threshold in kabsch_sander Function?

### ISSUE THREAD

**Issue by ShenWenHuibit** [mdtraj/mdtraj#1910]
Dear Developers,

I hope this message finds you well. For my calculations, I need to adjust the energy threshold for computing hydrogen bonds. However, the _mdtraj.kabsch_sander_ function does not provide an interface to adjust this parameter. Could you please guide me on how to modify the original code to change the energy threshold from _-0.5 kcal/mol_ to _-0.1 kcal/mol_?

Thank you for your assistance.

Best regards,
wenhui

**Comment by mattwthompson** [comment]
At the code level, it's set as a constant here: https://github.com/mdtraj/mdtraj/blob/934b2732aa7aaab3299c086b2f5abbe7013184ec/mdtraj/geometry/src/geometry.cpp#L355C11-L355C30

So that could be modified (in a fork) and experimented with. I don't think we're likely to make that a tunable parameter.

I don't actually know anything about the function, so there may be scientific downsides to messing with the energy cutoff
