### ISSUE TITLE
WebGL viewer secondaryStructure='ribbon' breaks with certain topologies

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#597]
I think ala2 is one of them. The problem is that the viewer relies on every `residue` having a CA atom, which is not the case for capping residues like NME.

**Comment by davidlmobley** [comment]
Same as #831, which can be closed.

**Comment by davidlmobley** [comment]
@rmcgibbo - it's probably an overstatement to say I'm using this for teaching; at this point it's more of a "dabble". However, it IS really nice to be able to show people how to do things (a simple minimization/simulation, setup of a particular system, whatever) with an iPython notebook and then embed a really quick view to show that the system is what's intended or the expected behavior happened. I expect I'll use TrajectoryView a lot in that context. It's less of an issue for students with experience in modeling (i.e. in my group) but if I'm showing undergrads how to do something, or teaching people inexperienced in modeling, it's a pain to have to get them to install additional software X, Y, and Z and explain to them how to use it just so they can see something simple that could easily be embedded in an iPython notebook. 

This particular bug is not high priority since the simple workaround is to not ask for secondaryStructure when it doesn't make sense, which is easy to explain.

**Comment by mpharrigan** [comment]
CC #1022
