### ISSUE TITLE
[FR] PDBx/mmCIF support

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#652]
wwPDB [recently announced](http://www.wwpdb.org/news/news_2014.html#18-September-2014) that large structures/complexes (100000+ atoms) will only be available in [PDBx/mmCIF](http://mmcif.wwpdb.org/) formats.

I'm assuming the current PDB loader won't be able to handle these files. Would support for these formats be handy?

**Comment by rafwiewiora** [comment]
Just refreshing this. I'm doing analyses with mdtraj on the whole database - as the wwPDB announced the FTP folder of `.pdb` files is no longer a complete database - large structures, which can't be described using one `.pdb` are missing (the website still lets you download those structures split into a few PDBs, but that's no good). Is anyone currently looking at copying the PDBx reader over from OpenMM?

**Comment by rmcgibbo** [comment]
I don't think anyone else is currently doing this. If you want to make the fix, that would be great :)

**Comment by rafwiewiora** [comment]
Alright, I'll get on it!

**Comment by swails** [comment]
One thing I'll point out is that ParmEd has an mmCIF parser as well, and it may be better suited for combing the PDB.  It pulls out more metadata from the PDB and mmCIF headers (and you can always extract *more* metadata through PRs).

But probably the big thing it has going for it is that ParmEd works under pypy.  The reason this was important for me is because I have needed to comb the PDB in the past for structures with particular experimental conditions, and the pure Python code in the PDB and mmCIF parsers run at least 3-5x faster under pypy (completely unmodified) compared to CPython.  Neither OpenMM nor MDTraj work with pypy.

A final observation -- the PDBx/mmCIF parser in OpenMM (which is the same one in ParmEd) is pure Python, and not well-optimized pure Python at that.  It is slow.  For reading a handful of structures, you're talking about taking seconds instead of milliseconds, so it doesn't matter.  When you're querying the PDB, the difference becomes significant (minutes to hours, I think).

**Comment by rafwiewiora** [comment]
Thanks a lot @swails, that's very useful to know!

**Comment by sbottaro** [comment]
Hi, 
I guess MDtraj does not support mmCIF format, is it correct?

**Comment by rmcgibbo** [comment]
@sbottaro: That is correct.

**Comment by sbottaro** [comment]
There seems to be a PDBx reader in OPENMM: 
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/pdbxfile.py

if someone could give me a couple of suggestions on how to port it into MDTRAJ, I can give it a try.

**Comment by peastman** [comment]
I'm reopening this issue because it's an important feature.  It would be very easy to copy over the implementation from OpenMM.  But alternatively, what about just using OpenMM directly?  That will be much more maintainable than cloning it.  The PDB classes in MDTraj were originally copied from OpenMM, but then no one kept them up to date and they're now years behind the current OpenMM release.

**Comment by rmcgibbo** [comment]
Installing OpenMM is not trivial, so I'd be -1 on directly using OpenMM here. Copying them over doesn't seem that bad.

**Comment by peastman** [comment]
It's just an extra conda dependency.

**Comment by rmcgibbo** [comment]
Lots of people don't use conda though to install mdtraj.

**Comment by peastman** [comment]
You're certainly free to copy over the code if you want to.  But it will be important to keep up to date with changes.

**Comment by ostrokach** [comment]
There are [MMCIFToDict](https://github.com/biopython/biopython/blob/164ebcd32f1f2cea3e507c17c4cda05dae1d7f7c/Bio/PDB/MMCIF2Dict.py#L14) and [MMCIFIO](https://github.com/biopython/biopython/blob/5a7dbd08445630582f954c79aff836cfae570808/Bio/PDB/mmcifio.py#L50) classes in BioPython which allow reading and writing mmcif files. Maybe there could be a discussion with the BioPython community about extracting that code into a small standalone package, which could then be used as a dependency both for MDTraj and BioPython? The code also can be easily Cythonized to provide an additional increase in performance

**Comment by peastman** [comment]
Reopening this again.  And can we please stop this insanity of a bot closing issues just because no one has commented on them in a while?  That doesn't mean the issue has gone away.

**Comment by peastman** [comment]
Can we please please please end this insanity of automatically closing unfixed issues just because no one has commented in while?

PDB is an obsolete file format.  PDBx/mmCIF has been the standard for years now.  This is a very high priority.

**Comment by rmcgibbo** [comment]
> Can we please please please end this insanity of automatically closing unfixed issues just because no one has commented in while?

I'm sure it's configured by some code in the rep. Feel free to file a PR to modify it.

**Comment by ijpulidos** [comment]
Hi. Just wanted to mention that there exists [pycifrw](https://bitbucket.org/jamesrhester/pycifrw/src/development/) which is installable both in conda and through pip. We have used this library for some of the topology refactor for [openff-toolkit](https://github.com/openforcefield/openff-toolkit/) and it does the job pretty well, as far as we can see.

**Comment by peastman** [comment]
If I were to create a PR using OpenMM to implement PDBx/mmCIF support, would you accept it?  I realize it isn't your preferred implementation, but it's something I can do quickly and easily, and it would be way better than not having any support at all.

**Comment by rmcgibbo** [comment]
Sure

**Comment by rmcgibbo** [comment]
Closing a ticket from 2014!
