### ISSUE TITLE
Bug in topology parser

### ISSUE THREAD

**Issue by stevenio** [mdtraj/mdtraj#710]
In my psf file, the first residue has residue ID 41, but if I select the this residue using the following script, the actual selected residue is residue 82 not 41. Is this a bug or intended "feature"?
```
import mdtraj
topo = mdtraj.load('my.dcd', top='my.psf').topology
topo.select("resid 41")
```

**Comment by rmcgibbo** [comment]
Can you post a link to the `.psf` file, so that we can check it out and try to track down the bug?

**Comment by swails** [comment]
@rmcgibbo -- the source of the bug is clear (to me at least, as I wrote it :)).  The PSF parser doesn't do anything with the residue number except check to see if another residue has started.  Largely a consequence of the fact that it was originally written from an Amber perspective, where residue (and atom) numbering is implicit.

I've looked more closely at the `mdtraj.Topology` class and I know how to fix it.  But that probably requires me to also go back and assign chains from the SEGID (because otherwise it may be possible to have two residues with the same sequence ID *and* name).

So this is behavior that I expect (it was only recently that I even saw a PSF file whose residues did not number from 1 to nres).

I will work on a fix (unless @rmcgibbo is worried about breaking compatibility).  In the meantime -- @stevenio, the residue ordering goes from 1 to N.

**Comment by rmcgibbo** [comment]
According to [the atoms selection docs](http://mdtraj.org/latest/atom_selection.html#keywords), the `resid` keyword is supposed to be the 0-based index of the residue.

**Comment by rmcgibbo** [comment]
Perhaps some data from the PSF file can be used for the `resSeq` field in the topology?

From the `Topology.add_residue function`: 

        resSeq : int, optional
            Residue sequence number, such as from a PDB record. These sequence
            numbers are arbitrary, and do not necessarily start at 0 (or 1).
            If not supplied, the resSeq attribute will be set to the
            residue's sequential (0 based) index.

**Comment by swails** [comment]
Ah, so this is not actually a bug, but documented behavior.  I should've checked that.

> Perhaps some data from the PSF file can be used for the resSeq field in the topology?

That's exactly what I had just found.  I could certainly send `resid` to `resSeq`, but as I said, I would also have to create a new chain for each SEGID.  Shouldn't be hard, but since there's no pressing bug to fix here, I'll probably have to put it off a little bit.  I'll open an enhancement issue as a reminder.

**Comment by rmcgibbo** [comment]
I should probably improve the atom selection docs, because this behavior is kind of confusing I think.

**Comment by swails** [comment]
It's what VMD does, right?

**Comment by stevenio** [comment]
Thanks everyone for taking a look at this issue. In VMD, "resid 41" refers to the residue ID that comes verbatim from the PSF file. On the other hand, "residue 41" refers to the 42nd residue (the first residue in the PSF is renumbered to 0). These definitions can be found at http://www.ks.uiuc.edu/Research/vmd/vmd-1.3/ug/node133.html#SECTION001010000000000000000 . MDTraj has both keywords, but they behave differently than in VMD. That's where my confusion originated. It would be very nice to be able to select residues just by their actual residue IDs. Manually calculating the residue numbers is error-prone, especially when it involves 0-based vs. 1-based indexing. 

In MDTraj documentation, the definition for "residue" says "(generally 1-based, but depends on topology)". In the testing case I posted earlier, both "resid" and "residue" use 0-based indexing. It would be very helpful to give user some information on MDTraj's expected behavior for specific cases, such as top='my.psf' vs. top='my.pdb'. In the short term, it will be nice to have current expected behaviors documented in detail.
