### ISSUE TITLE
md.compute_center_of_mass should use PBCs

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#783]
`md.compute_center_of_mass` should use periodic boundary conditions, but doesn't. cc @sryckbos

**Comment by rmcgibbo** [comment]
Here's one way to do it: http://en.wikipedia.org/wiki/Center_of_mass#Systems_with_periodic_boundary_conditions

**Comment by harish-srini** [comment]
Is this bug being addressed?
Otherwise, there should be some way to find the atomic mass of each atom from the universe.

**Comment by dwhswenson** [comment]
@harish-srini : The current `compute_center_of_mass` code will not give the correct results if your system wraps through a periodic barrier. However, it you first use the [`trajectory.image_molecules`](http://mdtraj.org/1.9.3/api/generated/mdtraj.Trajectory.html?#mdtraj.Trajectory.image_molecules) method, you should get back frames with the molecules "unwrapped." Then this isn't a problem. (You can also just use [`trajectory.make_molecules_whole`](http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html?#mdtraj.Trajectory.make_molecules_whole), which does a little less cleanup than `image_molecules`.)

If you want the mass of an atom, you can get it from the `Atom` object, as `atom.element.mass`. You can get that atom once you know its index (counting from 0) using `atom = trajectory.topology.atom(atom_index)`.

---

... and now for something completely different:

### Rant about circular center of mass

The approach that @rmcgibbo linked to on Wikipedia is ***not*** correct for most of our use cases. That method (call it the "circular center of mass") is useful if you have a truly periodic system, where there isn't a meaningful center of mass because there's no frame of reference in which the whole system can be in one unit cell (e.g., what's the "center of mass" in latitude/longitude for the continents on Earth's surface?). It can also be used as a rough (and relatively cheap) approximation to the center of mass.

To show that it does not give the same results as making molecules whole and doing a COM calculation would, let's just try it on a system that isn't wrapped around a box. Here's a 1D version with 2 particles (assume the box size is 1):

```python
>>> from math import sin, cos, atan2, pi
>>> x1 = 0.4; x2 = 0.7  # particle locations
>>> m1 = 2; m2 = 1      # masses
>>> (m1*x1 + m2*x2) / (m1 + m2)  # standard COM
0.5
>>> xi1 = cos(x1*2*pi); xi2 = cos(x2*2*pi)
>>> zeta1 = sin(x1*2*pi); zeta2 = sin(x2*2*pi)
>>> xi_bar = (m1*xi1 + m2*xi2) / (m1 + m2)
>>> zeta_bar = (m1*zeta1 + m2*zeta2) / (m1 + m2)
>>> ccom = (atan2(-zeta_bar, -xi_bar) + pi) / (2*pi)
>>> ccom
0.4815406335895149
```

Close, but not quite correct.

---

(Also, I have no idea why/when I subscribed to get notifications on this thread, but I guess I did! And I wrote the long rant here because this circular COM comes up on occasion, and now I'll have a place to point people to for an explanation.)

**Comment by rmcgibbo** [comment]
Yeah, I agree with you, @dwhswenson. Let's close this "bug".

**Comment by harish-srini** [comment]
@dwhswenson Thank you for the clarification!
