### ISSUE TITLE
Loading .gro in chunks

### ISSUE THREAD

**Issue by OndrejMarsalek** [mdtraj/mdtraj#842]
I wanted to read a large .gro file in chunks using `iterload`. Getting the first chunk takes a very long time and it seems like it is trying to parse the whole file. Using a shorter file (1 frame) is fine. I would expect either the same behavior as with other formats or an error message.

As a smaller issue, `iterload` did not accept the `top` keyword argument when called with a .gro file. It would be nice to be able to use the same code regardless of the format. I guess that would mean either ignoring the provided topology or using it to override the one parsed from the .gro file.

**Comment by rmcgibbo** [comment]
> Getting the first chunk takes a very long time and it seems like it is trying to parse the whole file. Using a shorter file (1 frame) is fine. I would expect either the same behavior as with other formats or an error message.

This issue covers the same ground as #809. `iterload` currently only has an optimized code path for dcd, xtc, h5, and lh5. For the other formats, it currently just loads the whole thing into memory and then yields the chunks.

The easy way to fix this is to add another `elif` statement before https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L506-L509. The more complete way to fix this is to make that section of code more generic so that each format doesn't need to be special-cased. It anyone wanted to take a stab at implementing either of these, that would be great.

> As a smaller issue, `iterload` did not accept the top keyword argument when called with a .gro file.

Right. It looks like there's a bug here: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L367. That line should be more inclusive, and cover the same formats as https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L126-L127.

**Comment by rmcgibbo** [comment]
This is fixed now.
