### ISSUE TITLE
Add support for asNumpy=True optional argument for Trajectory.openmm_positions()

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#875]
It's often possible to retrieve positions from OpenMM as a `simtk.unit.Quantity` wrapped `(natoms,3)` numpy array by specifying the `asNumpy=True` optional argument.  Would be very useful if the `Trajectory.openmm_positions()` function supported `asNumpy=True` as well.

**Comment by swails** [comment]
This was requested a long time ago, but I don't see the upside of this.  Unlike OpenMM, MDTraj depends explicitly on numpy.  If you want a numpy array, just take `Trajectory.xyz`, not `Trajectory.openmm_positions()`.  If you want units on those, you can multiply those on (this wasn't true when you opened this issue, but it is now).

But that's not even necessary, really, since MDTraj's coordinates are already in nm and so are compatible as-is.  All `openmm_positions()` does, in my understanding, is build everything into the `Vec3` object and add units.  So this request strikes me as an instruction to MDTraj to "express your numpy coordinates as a list of Vec3s... actually on second thought just use numpy instead". :)

**Comment by jchodera** [comment]
Can I sheepishly express how, as an outsider, that all sounds incredibly
confusing, inconsistent, and utterly nonintuitive?

**Comment by rmcgibbo** [comment]
I had always thought you were the consummate insider.

**Comment by rmcgibbo** [comment]
Remind me what the use case for adding this kwarg is? The only use for the `openmm_positions()` method, I thought, was to "export" the data for "import" into OpenMM -- like `context.setPositions(trajectory.openmm_positions())` [1]. Would adding another option help this import/export business? Or is there another use case for this method?

[1] As @swails pointed out, you don't really need it anyways. But if you're not sure how to get the positions into OpenMM and you're reading the docs, it might help.

**Comment by swails** [comment]
> Can I sheepishly express how, as an outsider, that all sounds incredibly
> confusing, inconsistent, and utterly nonintuitive?

Sounds like an argument for deprecating or doing away with `openmm_positions()` altogether to me :).  I was responding without any knowledge of your use-case (since you didn't actually say what it was). So I was merely pointing out that asking for `openmm_positions(asNumpy=True)` is really the same as just asking for the `xyz` attribute, which is a rather roundabout way of using the main `Trajectory` API.

As for units, MDTraj has its own private copy of `simtk.unit` that is adjusted for its own use (and privately imports `simtk.unit` if available).  As I mentioned before, you *really* don't need `openmm_positions()` at all.  Just use `xyz` to get coordinates, and those interact directly with OpenMM.  If you need to add units, add units, but MDTraj does not do that for performance reasons.

**Comment by jchodera** [comment]
Thanks!
