### ISSUE TITLE
 IBM

### ISSUE THREAD

**Issue by euhruska** [mdtraj/mdtraj#888]
Is it possible to get mdtraj working on a IBM cluster?

**Comment by swails** [comment]
Maybe?  Have you tried?

**Comment by euhruska** [comment]
No, it doesn't work

**Comment by euhruska** [comment]
It fails on 
```gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Imdtraj/rmsd/include -I/home/eh22/local/lib/python2.7/site-packages/numpy/core/include -I/home/eh22/local/include/python2.7 -c mdtraj/rmsd/_rmsd.c -o build/temp.linux-ppc64-2.7/mdtraj/rmsd/_rmsd.o -fopenmp -msse2 -O3 -funroll-loops
cc1: error: unrecognized command line option "-msse2" ```
Is the msse2 necessary?

**Comment by swails** [comment]
MDTraj uses explicit SSE vector instructions for several of its functions (like RMSD and distance calculations, I think).

You can modify `basesetup.py` to set `compiler_args_sse2` and `compiler_args_sse3` to empty lists instead of those compiler flags and see if that works.  I'm not sure that it will, since the IBM chips have a different architecture (and therefore possibly different instruction sets) than the standard x86_64 chips like AMD and Intel.

**Comment by euhruska** [comment]
Doesn't look like that. I gives then errors in mdtraj/rmsd/_rmsd.c.

**Comment by rmcgibbo** [comment]
Can you point me to the documentation for your c/cpp compiler? Does it
support SSE? What are the flags that it takes?

**Comment by euhruska** [comment]
It's a PowerPC64,  doesn't support SSE2. So I guess I have to switch clusters.

**Comment by jchodera** [comment]
Is it possible to skip the optimized Intel-specific code and fall back to a numpy RMSD computation on `ppc64le` architectures?

**Comment by rmcgibbo** [comment]
There's a bunch of SSE intrinsics in both the geometry modules and the RMSD. Most of the geometry modules have a runtime flag to not use the optimized version written in C and fall back to a slow pure python version, which is used inside the test suite. There is no such option for the RMSD. There's also no options in the build system to skip compilation of these modules.
