### ISSUE TITLE
Supported residue numbering schemes?

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#906]
Related to https://github.com/pandegroup/openmm/issues/1072 I am renumbering the ~20,000 water residues in my PDB files.  If I move all the waters into a separate chain `'W'`, are there some numbering schemes that are MDTraj-friendly that I could use in order to squeeze all 20,000 waters into a single chain?

**Comment by rmcgibbo** [comment]
The relevant code for writing PDBs, and fitting everything into the fixed width format is 

```
                    line = "ATOM  %5d %-4s %3s %s%4d    %s%s%s  1.00 %s          %2s  " % (
                        atomIndex % 100000, atomName, resName, chainName,
                        (res.resSeq) % 10000, _format_83(coords[0]),
                        _format_83(coords[1]), _format_83(coords[2]),
                        bfactors[posIndex], symbol)
                    assert len(line) == 80, 'Fixed width overflow detected'
```
iirc, this is the same as openmm

see https://github.com/mdtraj/mdtraj/blob/94e20821aa086f5c49e13b1317ef36251eb8d098/mdtraj/formats/pdb/pdbfile.py#L315

**Comment by jchodera** [comment]
If I wrap water residue numbers with `(index % 9999) + 1` where we may end up with two (nonsequential) waters that have the same residue sequence, will that cause problems on reading/manipulating/writing files?  The only kinds of operations we need to tackle are stripping of waters from these files (for now).

Do you think there's a better way to handle this?  Split waters into separate chains of up to 9999 waters each?  Use letters/numbers?

**Comment by rmcgibbo** [comment]
Honestly i'm not really sure.

**Comment by jchodera** [comment]
If you use `(res.resSeq) % 10000`, I'm guessing having `resSeq` contain letters will break that, at least.

**Comment by jaredsampson** [comment]
I realize this is an old thread, but since I ran into the converse problem (loading a PDB file with large atom/residue numbers written in a format not recognized by `mdtraj`), I thought I'd post here rather than create a separate issue.  There is a "hybrid-36" format that seamlessly handles residue numbering greater than 99999 atoms in a model or 9999 residues in a chain, with a reference implementation in [cctbx](https://github.com/cctbx/cctbx_project/blob/666f100f60722b554cc7f8e440eb14bfe9a27f8f/iotbx/pdb/hybrid_36.py).

Basically, up to those limits it uses base 10 numbers, but starting with atom 100000 or residue 10000, it switches to a base 36 encoding, using the character set `[0-9A-Z]`.  The above reference implementation is open source with a permissive license, so could be easily incorporated into `mdtraj`.

I'm working on a [branch](https://github.com/jaredsampson/mdtraj/tree/hybrid-36) in my fork to allow reading of numbers in hybrid-36-format, which is used by Maestro (and others, including Phenix, for one) for residue and atom numbers in the water chains when saving PDB frames from most of my Desmond simulations.  Would be happy to accept implementation help and/or suggestions for writing hybrid-36-formatted PDBs from `mdtraj` as well.  For example, one question I have for maintainers is, would the relevant encode/decode functions be better placed in `pdb/pdbfile.py` or `pdb/pdbstructure.py` (or someplace else, perhaps a new file, `hybrid36.py`)?  Presumably I could simply copy the `cctbx` license and all required functions from the reference implementation and be good to go.  (Alternatively, one could use `cctbx` directly if it is available as an optional dependency, printing an error message if hybrid-36 numbers are encountered and cctbx is not installed, but that'd be a pretty heavyweight solution for such a limited problem.)
