### ISSUE TITLE
RMSD calculation for multiple mutants

### ISSUE THREAD

**Issue by steven-albanese** [mdtraj/mdtraj#907]
I'm trying to calculate RMSDs for multiple trajectories, each of which contains a different mutant of the same protein, with the wild type protein as reference. If I slice out the alpha carbons, will the fact that the topologies are different for each of these mutants cause a problem?

**Comment by rmcgibbo** [comment]
The RMSD calculation is based on a correspondence between atoms in the two trajectories -- it's the distance from atom 1 in the first frame to atom 1 in the second frame, combined with the distance from atom 2 in one to the other atom 2, etc. So if, for example, your mutants were renumbered in such a way that the `i`th atom in each trajectory did not "correspond" to the `i`th atom in the other trajectory, then there would be a problem. Otherwise, no.
