### ISSUE TITLE
Element detection in the .gro reader fails for element names of len > 1

### ISSUE THREAD

**Issue by ctk3b** [mdtraj/mdtraj#909]
I was trying to read a .gro file which contained `CAL` and `CLA` ions. Using the [current logic](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/gro.py#L315) in the .gro reader, these are identified as carbons because everything after the first character is discarded.

Is there any reason not to do something like in the [pdb reader](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbstructure.py#L759) or in [parmed](https://github.com/ParmEd/ParmEd/blob/master/parmed/periodic_table.py#L291-L296)?

**Comment by swails** [comment]
> Is there any reason not to do something like in the pdb reader or in parmed?

FTR, ParmEd behaves the same as mdtraj for these two atom types.  It first tries to match the first letter.  Failing that, it tries matching the first two.  Failing that, it gives up. The reason I do that is simple:

- `CA` atoms are the alpha-carbon in every amino acid
- I'm lazy

What the first one means is that the logic for distinguishing what is a calcium and what's a carbon is going to be very complex, since it will need a lot more information than just the atom name to more reliably determine the element.  So using atom name alone to determine what the element should be is borderline madness :).

By far the most reliable way to determine elements are, in order:

- An explicit atomic number
- An explicit element name (e.g., the last columns in a PDB file)
- Atomic mass (can be thrown off by, e.g., hydrogen-repartitioning)
- \*insert fillers here\*
- atom name
- closely followed by `random.choice(list_of_elements)`

IMO the problem is the GRO file format, which makes this information virtually impossible to figure out.  You're better off using either the Gromacs topology file directly or a PDB with element information if the element is important.

**Comment by ctk3b** [comment]
Ah gotcha, should have read the note in parmed :+1:

**Comment by rmcgibbo** [comment]
We have various tables of different atoms names, residue names, etc in https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/residue_names.py. If anyone wants to make a mapping of "special" atom names -> element symbol, we could add that.

**Comment by swails** [comment]
> If anyone wants to make a mapping of "special" atom names -> element symbol, we could add that.

I don't have a personal use for it, but it's a good solution if you had to have better name->element prediction.  It's still worse IMO than using the mass (or atomic number/element symbol, obviously), but would clearly make things better than the status quo.

**Comment by rmcgibbo** [comment]
I don't think gro files contain the mass though.

**Comment by ctk3b** [comment]
Right, this is probably the only way to get more reliable elements out of gro files.

**Comment by swails** [comment]
> I don't think gro files contain the mass though.

They don't.  As I mentioned before, GRO files make this information borderline impossible to figure out in an unambiguous way.  A mapping would improve things in cases like this, but there's always a decent chance at a mis-assignment.  The Gromacs top file is a much better choice, as is a properly-built PDB (i.e., one that has the element names printed in the last two columns)

**Comment by rmcgibbo** [comment]
Our goal is always to do the best we can though, not to necessitate that the user have other files.

**Comment by swails** [comment]
> Our goal is always to do the best we can though, not to necessitate that the user have other files.

There have to be *some* limits to this.  For instance, the name `CA` should always refer to a carbon, since that is by far the most common.  If someone names their calcium a CA, you'd have to look at the context to figure out its element  -- easy for a human, complicated for a computer.  It's rare enough that getting it wrong might be an OK price to pay for keeping the code manageable.

The name map is certainly an improvement, and I'm +1 if someone wants to tackle that, but it's going to start out too small with not enough entries to hit even the majority of corner cases at first, most likely.  It'll get better with time, but my point is that regardless, relying on atom names in general to get you the element is a bad way to go if element assignment is very important to your application.

The reason it's not on todo list is because either element identity is unimportant to me, or I use a file that contains that information (or unaltered masses) to begin with.
