### ISSUE TITLE
Memory issues with mdtraj 

### ISSUE THREAD

**Issue by steven-albanese** [mdtraj/mdtraj#932]
Currently loading in trajectories in groups of 10, using `slice` to look at frames of interest and then `join` to concatenate them into one long frame, as follows: 

````
    for clone in range(n_clones):
        traj = md.load(os.path.join(input_data_path, "run%d-clone%d.h5" % (run, clone)))
        end_frame = len(traj)
        short_traj = traj.slice(range(min_frame,end_frame), copy=True)

        if clone == 0:
            final_traj = short_traj
        else :
            final_traj =final_traj.join(short_traj)

        del traj  
        del short_traj
````

I then use `md.compute_contacts` on `final_traj`. Something in this process is putting a strain on memory resources (on the order of 50G). Are there either other ways to do this or things I'm missing in trying to manage memory usage?

**Comment by rmcgibbo** [comment]
If your trajectories are too large to load in memory, you can use `iterload` to stream through the trajectories, or `md.open` to open the file handle, and then `seek` to the appropriate frame.

**Comment by steven-albanese** [comment]
The trajectories themselves aren't overly large! It seems like I'm accumulating garbage somewhere as I iterate through the for loop posted above. I tried to address this by using `del

**Comment by steven-albanese** [comment]
Earlier, I was loading all of the trajectories in using `dataset.MDTrajDataset` from msmbuilder and then iterating over the traj objects in the dataset and that seemed to give me less memory problems (but was very slow)

**Comment by mpharrigan** [comment]
The dataset object only loads one trajectory at a time into memory as needed

**Comment by swails** [comment]
Take out the `compute_contacts` command and look at memory usage.  It's important to determine if there are some ghost references sticking around that prevents the trajectories and their copies from being collected (note, `del` only decrements the refcount -- if it doesn't go to 0 for that object, the memory it's using isn't freed), or if `compute_contacts` is building up some ridiculously huge list of pairs to evaluate.

The latter could certainly blow memory if it's looking at all pairs between all atoms for all frames.  Disclaimer is that I'm not sure if that last one is possible, since I don't know the details of how `compute_contacts` is implemented or how you're trying to use it.

**Comment by rmcgibbo** [comment]
One good debugging method might be to work with a scaled down version of your problem that you can run quickly and repeatedly, and then use a tool like https://pypi.python.org/pypi/memory_profiler.

**Comment by gph82** [comment]
Hi, just a sanity-check: What does "one long frame" mean? Plus, how many atoms are we talking about here? If using "all"...doesn't this scale pretty badly?

**Comment by mpharrigan** [comment]
I assume he meant one long trajectory, based on the code presented

**Comment by steven-albanese** [comment]
Sorry, I did mean one long trajectory!
