### ISSUE TITLE
ImportError: IntSliderWidget

### ISSUE THREAD

**Issue by ChrisWellsWood** [mdtraj/mdtraj#960]
Hello,

I really like the look of mdtraj, especially the iPython notebook trajectory view integration, however I'm having a problem. I've installed using `conda install -c omnia mdtraj` but when I try `from mdtraj.html import enable_notebook, TrajectoryView', I receive the following error:

```
/Users/ChrisWood/anaconda/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The
'IPython.html' package has been deprecated. You should import from 'notebook' instead.
'IPython.html.widgets' has moved to 'ipywidgets'.
'IPython.html.widgets` has moved to 'ipywidgets'.", ShimWarning)
```

I dug around in the `html/__init__.py` and removed the try/except and the error is caused when TrajectoryView is imported, and it gives the following error:

```      6 
      7 from IPython.display import display, Javascript
----> 8 from ipywidgets import DOMWidget, IntSliderWidget, ContainerWidget
      9 from IPython.utils.traitlets import (Unicode, Bool, Bytes, CInt, Any,
     10                                      Dict, Enum)

ImportError: cannot import name IntSliderWidget
```

I'm not sure why this is happening. Anaconda is up to date (ipython > 4.0, widgets installed), and it's happening on both OSX (El Capitan) and Linux (SL6). Any idea what's going wrong?

Thanks very much!

**Comment by cxhernandez** [comment]
This error is due to `IPython.html`'s recent migration to `ipywidgets`. The next release of MDTraj (v1.5.0) should fix this issue (see https://github.com/mdtraj/mdtraj/issues/927 and https://github.com/mdtraj/mdtraj/pull/935). If you'd like, you can install the development version from this repo, which should work just fine on OSX and Linux.

**Comment by mpharrigan** [comment]
If you want to use the development version, you can download the source from github and install with
```
python setup.py install
```
(note that this may not automatically get all the dependencies you need)

or you can use conda to install the `mdtraj-dev` package, which is built for every pull request
```
conda install -c mdtraj-dev
```

or you can wait ~a week for us to release a new official version (#959)

I'm going to close this issue because it's been fixed in `master`

**Comment by ChrisWellsWood** [comment]
Nice one, thanks very much. I installed from the repo using the setup.py and it seems to be working.
