### ISSUE TITLE
add support for protonated residues 

### ISSUE THREAD

**Issue by msultan** [mdtraj/mdtraj#996]
We need to add support for the protonated forms of several amino acids including Asp, Glu and His. I am not sure which set of files need to change for this to happen though.

**Comment by swails** [comment]
In what ways is it not currently supported?

**Comment by msultan** [comment]
I think the residue names files in ```residue_names.py``` is missing things like protonated glu/asp and delta protonated histidine. I am uncertain how to wrangle up the common naming conventions though.

**Comment by msultan** [comment]
Is there a list on the internet somewhere for residue naming conventions across platforms? @swails you might have the most comprehensive one given parmed.

**Comment by swails** [comment]
The PDB standard dictates that all protomers and tautomers have the same name.  So ASP refers to either protonated or deprotonated aspartate/aspartic acid.

Some programs deviate from this because they require residue names to map to *unique* sets of connected atoms.  But there is certainly no "standard" here.  I know what Amber does, and I can easily figure out what CHARMM does, but OpenMM and the PDB don't use different names.

**Comment by msultan** [comment]
I agree with the standard but we should cover the basic naming schemes for common ffs across different platforms imho.

**Comment by mpharrigan** [comment]
There's some discussion of this in #637 

There are already aliases for common non-standard residue names https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/data/pdbNames.xml

**Comment by swails** [comment]
The notable ones missing from Amber that I can see are ASH, GLH, CYX, CYM, and LYN (different protomers of ASP, GLU, CYS, and LYS).

I can open a PR for those, but if we're using a non-PDB topology (e.g., a prmtop), do the name replacements still get loaded and applied?  My memory tells me no...
